
/* these are the words of English and their crosponding meaning in Tigringa language. almost all English words are listed here
// and their meaning in tigringa is also being there as a value of the english word.still new words are going to be embeded here
in this dictionary.*/

 var obj={"a little":	["ንእሽቶይ"	,"ቁሩብ"	,"ውሕድ"]	,
"a long time":	"ነዊሕ ግዝ"			,
"a lot":	"ብዙሕ"			,
"abandon":	["ገደፈ"	,"ረጥረጠ"]		,
"abandonment":	"ርጥረጣ"			,
"abbot":	"ኣባ"			,
"ability":	["ጥበብ"	,"ክእለት"	,"ብቕዓት"]	,
"able":	["ጥበባዊ","ክእለታዊ"]		,
"above":	"ኣብ ልዕሊ"			,
"abrupt":	"ሃንደበት"			,
"abruptly":"ብጋህዲ"			,
"abscess":	"ሓገል"	,
"absence":	"ብኩራት"		,
"absent":	"ብኹር"			,
"absent ":	"ቦኾረ"			,
"absent minded":	"ዝንጉዕ"			,
"absent mindedness":	"ምዝንጋዕ"			,
"absolute":	"ፍጹም"			,
"absolutely":	"ብፍጹም"			,
"absolve":	"ፈተሐ"			,
"accustomed":	"ኣልመደ"			,
"ache":	"ቓንዛ"			,
"achieve":	"ፈጸመ"			,
"achievement":	"ጭብጢ"			,
"aching":	"መቐንዘዊ"			,
"achy":	"ቓንዛዊ"			,
"acidic":	"መጺጽ"			,
"acorn":	"ፍረ ኦክ"			,
"acquaint":	["ምልላይ"	,"ምፍላጥ"]		,
"acquaintance":	["ሌላ"	,"ፍልጠት"]		,
"acquire":	"ረኸበ"			,
"acquit":	["ፈተሐ"	,"ንጹህ"	,"ቕንዕና"]	,
"acquittal":	"ምኽፋል ዕዳ"			,
"act":	["ገበረ"	,"ምግባር"	,"ምትውሳእ"]	,
"action":	["ተግባር"	,"ግብሪ"]		, 
"actively":	["ተግባራዊ"	,"ግብራዊ"]		,
"activity":	["ንጥፈት"	,"ስራሕ"]		,
"actor":	"ተዋሳአይ"			,
"actors":	"ተዋሰእቲ"			,
"actress":	"ተዋሳኢት"			,
"advantage":	"ረብሓ"			,
"adventure":	"ዕንደራ"			,
"adversary":	"ተጻራሪ"			,
"advertisement":	"ረክላም"			,
"advice":	"ምኽሪ"			,
"advise":	"መኸረ"			,
"adviser":	"ኣማኻሪ"			,
"advocate":	["ጠበቓ"	,"ወከል"	,"ሐገዝ"]	,
"advocate":	["ምውካል"	,"ምሕጋዝ"]		,
"advocator":	["ወካሊት"	,"ሐጋዚት"]		,
"advocator":	["ወካሊ"	,"ሓጋዚ"]		,
"advocator":	["ወከልቲ"	,"ሓገዝቲ"]		,
"aerate":	"ኣናፈሰ"			,
"affect":	["ሳዕቤን"	,"ተንከፈ"]		,
"affection":	["ስምዒት"	,"ፍቕሪ"]		,
"affectionate":	["ስምዒታዊ"	,"ፈቃር"]		,
"affirm":	["ምርግጋጽ"	,"ኣመስለ"]		,
"affirmable":	"ርግጻዊ"			,
"affirmably":	"ብርግጽ"			,
"afford":	["ምኽኣል"	,"ኪኸፍል"]		,
"affordable":	"ክኣል"			,
"air":	["ንፋስ"	,"ኣየር"]		,
"airplane":	"ነፋሪት"			,
"airport":	"መዕረፍ ነፈርቲ"			,
"alarm":	"መጠንቀቕታ"			,
"alarm":	"ምጥንቓቕ"			,
"alight ":	"ተባርዐ"			,
"align":	["ረበበ"	,"ምግጣም"	,"ምስራዕ"]	,
"alive":	"ሂወታዊ"			,
"alive":	["ነበረ"	,"ምህላው"]		,
"all":	"ኩሉ"			,
"alliance":	["ኪዳን"	,"ምሕዝና"	,"ምሕዝነት"]	,
"allow":	"ኣፍቀደ"			,
"alone":	["እንኮ ንብሕቶ"	,"ጽሙዋ"]		,
"alphabet":	"ፈደል"			,
"already":	"ድሮ"			,
"always":	"ኩሉ ግዜ"			,
"amateur":	"ተልመደን"			,
"amaze":	["ኣገረመ"	,"ምግራም"	,"ምድናቕ"]	,
"amazed":	["ኣገራሚ"	,"ኣደናቒ"]		,
"amazedly":	"ብምግራም"			,
"amazing":	"ሃንደበታዊ"			,
"ambition":	"ትምኒት"			,
"ambulance":	"ኣምቡላንስ"			,
"amenable":	"ምእዙዝ"			,
"amends":	"ጽገና"			,
"amount":	["ድምር"	,"ክንደይ"]		,
"ample":	"ገፊሕ"			,
"amuse":	["ኣስሓቐ"	,"ኣዘናገዐ"]		,
"amusement":	"ምዝንጋዕ"			,
"amusing":	"መስሓቕ"			,
"ancestor":	"ወለዶ"			,
"ancient":	"ጥንታዊ"			,
"angel":	"መልኣኽ"			,
"anger":	["ሕርቓን"	,"ኩራ"]		,
"anger":	["ምሕራቕ"	,"ምኹራይ"]		,
"angle":	"ኩርናዕ"			,
"angry":	["ሓራቕ"	,"ኾራዪ"]		,
"angry":	["ኾራይት"	,"ኩርፍፍቲ"]		,
"angry":	"ኾርፋፍ"			,
"anguish":	"ጭንቀት"			,
"animal":	"እንስሳ"			,
"animate":	"ህይወት ሃበ"			,
"ankle":	["ግንቦ እግሪ"	,"ኩርናዕ እግሪ"]		,
"announce":	"ኣወጀ"			,
"announcement":	["መግለጺ"	,"ታእዋጅ"	,"መልእኽቲ"]	,
"annoy":	"ኣሕረቐ"			,
"annoyed":	"ኮረየ"			,
"annual":	"ዓመታዊ"			,
"answer":	"መልሲ"			,
"answer":	"መለሰ"			,
"ant":	"ጻጸ"			,
"ant hill":	"ጉላ"			,
"antenna":	"ቅርኒብ ሓሸራ"			,
"anticipated":	"ኣቐዲምካ ዝግበር"			,
"antique":	"ጥንታዊ"			,
"antiquity":	"ጥንቲ"			,
"anvil":	"ወጸቓ"			,
"anxiety":	["ሃንቀውታ"	,"ጭንቀት"	,"ሽግርግር"]	,
"anxiety":	"ትሻቐለ"			,
"anxious":	"ሽጉር"			,
"any":	"ኩሉ"			,
"anybody":	"ሰብ"			,
"anything":	"ገለኳ"			,
"apartment":	"ገዛ"			,
"apologize":	"ይቕረታ ሓተተ"			,
"appalling":	["ኣሰንባዲ"	,"ኣገራሚ"	,"ኣደናቒ"]	,
"apparatus":	"መሳርሒ"			, 
"appeal":	["ይግባይ"	,"ሕቶ"]		,
"appeal":	"ምሕታት"			,
"appear":	"ተራእየ"			,
"appear suddenly":	"ተቐልቀለ"			,
"appearance":	"ምቕልቃል"			,
"appease":	"ኣህደአ"			,
"applaud":	["ኣንጨብጨበ"	,"ምጥቓዕ"	]	,
"applauder":	"ኣጣቓዒት"			,
"applauder":	"ኣጣቓዓይ"			, 
"applauder":	"መጣቐዕቲ"			,
"applause":	["ጨብጨብታ"	,"ጣቕዒት"]		,
"apple":	["ቱፋሕ"	,"ቱፋህ"	,"ሜለ"]	,
"apple tree":	"ቱፋሕ ገረብ"			,
"application":	"ተገዳስነት"			,
"applied":	"ትጉህ"			,
"apply":	"ሓተተ"			,
"apply for":	"ጠለበ"			,
"appoint":	"ሰየመ"			,
"appointment":	"ቆጸራ"			,
"appraise":	"ገመተ"			,
"appreciable":	["ተነካኢ"	,"ፉሉጥ"	,"ሞገስ"]	,
"appreciate":	["ኣሞገሰ"	,"ምምስጋን"]		,
"apprenticeship":	"ልምምድ"			,
"approach":	"ቀረበ"			,
"approval":	"ምጽዳቕ"			,
"approve of":	"ኣጽደቐ"			,
"apricot tree":	"ሚሽሚሽ ገረብ"			,
"April":	"ሚያዝያ"			,
"apron":	"ግርምብያለ"			,
"aptitude":	"ቅሊ"			,
"arc":	["ቀሸም"	,"ቀስቲ"]		,
"ardent":	"ረሳን"			,
"area":	["ዞባ"	,"ቦታ"]		,
"argue":	["ተኻትዐ"	,"ምክታዕ"	,"ምቁያቕ"]	,
"arithmetic":	"ቁጽሪ"			,
"arm":	"ቅልጽም"			,
"arm":	"ኣዕጠቐ"			,
"armchair":	"ኩርሲ"			,
"armistice":	"ግዚያዊ"			,
"arms":	"የእዳዎ"			,
"army":	"ሰራዊት"			,
"arouse":	"ተበራበረ"			,
"arrange":	["ኣዳለወ"	,"ምምዕራይ"]		,
"arrest":	"ማእሰርቲ"			,
"arrest":	"ኣሰረ"			,
"arrive":	"በጽሐ"			,
"art":	["ጥበብ"	,"ስእሊ"]		,
"artery":	["ኣርተሪ"	,"ሰራውር"]		,
"article":	"ዓንቀጽ"			,
"artificial lake":	["ጋብላ"	,"ዒላ"]		,
"artist":	["ጥበበኛ"	,"ሳኣላይ"]		,
"as far as":	"ክሳብ"			,
"as many":	"ብጣዕሚ"			,
"as much":	"ብጣዕሚ"			,
"as well":	"ከምኡውን"			,
"ascent":	"ዕርገት"			,
"ashamed":	"ዘሕፍር"			,
"ashes":	"ሓሙኹሽቲ"			,
"ask":	"ሓተተ"			,
"assassin":	"ቀታሊ"			,
"assassinate":	"ቀተለ"			,
"assemble":	["ኣላገበ"	,"ምግጣም"]		,
"assembly":	["ባይቶ"	,"ጉባኤ"]		,
"assert":	"ኣረጋገጸ"			,
"assess":	"ገመተ"			,
"assign":	"መዘዘ"			,
"assist":	"ሓገዘ"			,
"assistance":	"ሓገዝ"			,
"association":	"ማሕበር"			,
"assurance":	"መተኣማመኒ"			,
"astonish":	["ኣገረሀ"	,"ኣገረመ"]		,
"astonished ":	"ተገረመ"			,
"astonishment":	"ድንጽዉና"			,
"at":	"ኣብ"			,
"at last":	"ኣብ መዳእታ"			,
"at least":	["ብብዚሒ"	,"ብዉሕድ"]		,
"atmosphere":	"ሃዋህው"			,
"attach oneself to":	"ጠበቐ"			,
"attachment":	"ጥብቀት"			,
"attack":	"ኣጥቅዐ"			,
"attempt":	"ፈተነ"			, 
"attend":	"ተኻፈለ"			,
"attention":	["ጥንቃቐ"	,"ኣድህብ"]		,
"attentive":	["ጥንቁቕ"	,"ኣድሃቢ"]		,
"attentively":	"ብጥንቃቐ"			,
"attorney":	"ጠበቓ"			,
"attract":	"ማረኸ"			,
"attractiveness":	"ማርኾት"			,
"attribute":	"መዘዘ"			,
"August":	"ነሓሰ"			,
"auntaunt":	["ኣሞሓትነ"	,"ሓትኖ"]		,
"author":	["ደራሲ"	,"ደራሳይ"	,"ጸሓፋይ"]	,
"authority":	"ሰበ ስልጣን"			,
"authorize":	"ኣፍቀደ"			,
"automatic":	"ኣውቶማቲክ"			,
"autumn":	"ቀውዒ"			,
"autumnal":	"ናይ ቀውዒ"			,
"avenge":	"ሕነ ፈደየ"			,
"avenue":	"ዓብይ ጎደና"			,
"avert":	"ፈላለየ"			,
"avoid":	"ወገደ"			,
"awakening":	"ሰዓት ደወል"			,
"award":	"ብልጫ"			,
"aware of":	"ፈለጠ"			,
"away":	"ወሰደ"			,
"away":	"ኣለየ"			,
"axe":	"ፋስ"	,
          "babble":	"ኣዕዘምዘመ"			,
"baby":	"ሕጻን"			,
"bachelor":	"ዘይምርዕዉ"			,
"back ":	"ሕቆ"			,
"back ":	"ድሕሪት"			,
"back away":	"ደሓረ"			,
"back":	["go"	,"ተመለሰ"]		,
"back":	["take"	,"መለሰ"]		,
"background":	"ማዓሙቕ"			,
"backward":	"ድሕሪት"			,
"bad":	"ሕማቕ"			,
"bad luck":	"ሕማቕ ዕድል"			,
"bag":	"ሳንጣ"			,
"baggage":	["ባልጃ"	,"ኣቑሑ ጉዕዞ"]		,
"bait":	"መቑለብ ዓሳ"			,
"baker":	"ሰንካቲ"			,
"baker's shop":	"እንዳ ባኒ"			,
"balance":	"ሚዛን"			,
"balcony":	"ባልኮን"			,
"ball":	"ኩዕሶ"			,
"ban":	"ወገደ"			,
"banana":	"ባናና"			,
"band":	"መጥመሪ"			,
"bandage":	["ኣተሓኻኸማ"	,"ቺረቶ"]		,
"bandit":	"ሽፍታ"			,
"bang":	["ዘበጠ"	,"ምህራም"	,"ምዝባጥ"]	,
"bang on":	"ወቕዐ"			,
"bank":	"ባንክ"			,
"banker":	"ባንከኛ"			,
"baptism":	"ጥምቀት"			,
"bar":	["መደንደል"	,"ቤት መስተ"]		,
"barbed wire":	["ትሪኮላታ"	,"እሾኽ"]		,
"barge":	"ባርካ"			,
"bark":	["ቅላጥ"	,"ቅላጥ ዕንጨይቲ"]		,
"bark":	"ነብሐ"			,
"barley":	"ስገም"			,
"barn":	"መኽዘን አኽሊ"			,
"barometer":	"ባሮሜተር"			,
"barrel":	["መድፍዕ"	,"ፊስቶ"]		,
"barren":	"መኻን"			,
"barrier":	"መጋረዲ"			,
"barring":	"ግድብ"			,
"barrister":	"ጠበቓ"			,
"basil":	["ቤዚል"	,"ባዘሊኮ"]		,
"basin":	"ጋብላ"			,
"basket":	"ዘንቢል"			,
"bath":	"ምሕጻብ ነብሲ"			,
"bathe":	"ተሓጸበ"			,
"baton":	"ዘንጊ"			,
"battalion":	"ቦጦሎኒ"			,
"battle":	"ውግእ"			,
"battlefield":	"ዓውደ ውግእ"			,
"bazaar":	["ባዛር"	,"ዕዳጋ"]		,
"be":	["እዩ","ኣሎ"]		,
"beach":	"ገምገም ባሕሪ"			,
"bead":	"ሉል"			,
"beam":	"ጩራ"			,
"bean":	"ፋጆሊ"			,
"beans":	"ባሎንኌ"			,
"beans stew":	"ትምቲሞ"			,
"bear":	"ድቢ"			,
"bear out":	"ኣጸረየ"			,
"beard":	"ጭሕሚ"			,
"beast":	"እንስሳ"			,
"beat":	["ሃረመ"	,"ሰዓረ"]		,
"beautiful":	"ጽቡቕ"			,
"beauty":	"ጽባቐ"			,
"become":	"ኮነ"			,
"become rich":	"ሃብተመ"			,
"bed":	["ዓራት","ደቀሰ"]			,
"bedroom":	"መደቀሲ ከፍሊ"			,
"bee":	"ንህቢ"			,
"beech":	"ቢቸ"			,
"birth":	"ሓረሰት"		, 
"birthday":	"ልደት"			,
"biscuit":	"ቢስኮቲ"			,
"bishop":	"ኣቡን"			,
"bit":	"ቁራጽ"			,
"bite":	"ነኸሰ"			,
"bitter":	"መሪር"			,
"bizarre":	"ዘገርም"			,
"black":	"ጸሊም"			,
"black pepper":	"በርበረ ጸሊም"			,
"blackbird":	"ዋሪ"			,
"blackboard":	"ሰሌዳ"			,
"bladder":	"ፊሕኛ"			,
"blame":	"ከሰሰ"			,
"blanket":	"ኮቦርታ"			,
"blaze":	"ተቓጸለ"			,
"bleat":	"እምቤዕ"		,
"bleed":	"ደመየ"			,
"bless":	"መረቐ"			,
"blessing":	"ምርቓ"			,
"blind":	"ዓይነ ስዉር"			,
"block":	"ወተፈ"			,
"blond":	"ጨዓይ"			,
"blood":	"ደም"			,
"bloody":	"ደማዊ"			,
"bloom":	"ዓምበበ"			,
"blossom":	"ዕምባባ"			,
"blot":	"ንጣብ ርስሓት"			,
"blotting paper":	"ሰታይ ቀለም"			,
"blouse":	"ካሚሻ"			,
"blow":	["ነፈሰ"	,"ኡፍ በለ"]		,
"blow up":	["ተባርዐ"	,"ነፍሐ"]		,
"blue":	"ሰማያዊ"			,
"board":	"ፈራዶ"			,
"boast":	"ፈከረ"			,
"boat":	"መርከብ"			,
"boathouse":	"ገበላ"			,
"bobbin":	"ቁኒን"			,
"body":	"ነብሲ"			,
"boggy":	"ጭቃዊ"			,
"boiled beef":	"ብሱል ስጋ"			,
"bomb":	"ቦምባ"			,
"bombard":	"ደብደበ"			,
"bombardment":	"ደብዳብ"			,
"bone":	"ዓጽሚ"			,
"bones":	"ዓጽሚ"			,
"book":	"መጽሓፍ"			,
"booklet":	"መጽሓፍ ጸብጻብ"			,
"bookstore":	"ድኳን መጻሕፍቲ"			,
"boot":	"ነዊሕ ሳእኒ"			,
"border":	"ዶብ"			,
"boring":	"መሰልከዊ"			,
"born":	"ተወለደ"			, 
"borrow":	"ተለቀሐ"			,
"boss":	"ኣስራሒ"			,
"bother":	"ኣጨነቐ"			,
"bottle":	"ጥርሙዝ"			,
"boulevard":	"ገፊሕ ጎደና"			,
"boundary":	"ደረት"			,
"bouquet":	"ጥማር"			,
"boutique":	"ድኳን"			,
"box":	"ሳንዱቕ"			,
"boy":	"ወዲ"			,
"boyhood":	"ንእስነት"			,
"brace":	"ኣሰረ"			,
"bracelet":	"በናጅር"			,
"brain":	"ሓንጎል"			,
"branch":	"ቃራና"			,
"brass band":	"ጥሩምበኛታት"			,
"brave":	"ተባዕ"			,
"bravery":	"ትብዓት"			,
"bread":	"ባኒ"			,
"bread":	"ቂጫ"			,
"bread":	"thick unleavened"			,
"breadth":	"ስፍሓት"			,
"break up":	"ሰበረ"			,
"breakdown":	"ስባር"			,
"breakfast":	"ቁርሲ"			,
"breaking open":	"ስባር"			,
"breast":	["ኣፍልቢ"	,"ጡብ"]		,
"breath":	"ትንፋስ"			,
"breathe":	"ኣተንፈሰ"			,
"breed":	"ኣዕበየ"			,
"brick":	"ሑጡብ"			,
"bridge":	"ድልድል"			,
"brief":	"ብሓጺሩ"			,
"briefcase":	"ቦርሳ"			,
"bright":	"ብሩህ"			,
"brightness":	"ብራሃን"			,
"brilliant":	"ኣንጸባረቒ"			,
"bring":	"ኣምጸአ"			,
"bring close":	"ቀረበ"			,
"bringing together":	"ኣኼባ"			,
"broad":	"ገፊሕ"			,
"brochure":	"መጽሓፍ ጸብጻብ"			,
"broom":	"መኾስተር"			,
"brother":	"ሓወ"			,
"brotherly":	"ሕውነታዊ"			,
"brown":	"ቡናዊ"			,
"brush":	"ኣስባስላ"			,
"brutal":	"ኣረመና"			,
"bucket":	"ሳንኮሎ"			,
"buddy":	"መሓዛ"			,
"build":	"ሃነጸ"			,
"building":	"ህንጻ"			,
"bulb":	"ኣምፑል"			,
"bulk":	"እኩብ"			,
"bull":	"ኣርሓ"			,
"bullet":	"ጥይት"			,
"bunch":	"ጥማር"			,
"bundle":	"ጥቕላል ባኮ"			,
"burden":	"ጽዕነት"			,
"burgle":	"ሰረቐ"			,
"burial":	"ቀብሪ"			,
"burn":	"ነደደ"			,
"burning":	"ዘቃጽል"			,
"burst":	"ነቶገ"			,
"bush":	"ቆትቋጥ"			,
"bushy":	"ጽዑቕ"			,
"business":	"ጉዳይ"			,
"but":	["ግን"	,"ግና"	,"ጌና"]	,
"butcher's shop":	"እንዳ ስጋ ሓሰማ"			,
"butter":	"ጠስሚ"			,
"butter milk":	"ማይ ጨባ"			,
"butterfly":	"ጽምብላሊዕ"			,
"button":	"መልጎም"			,
"buy":	"ዓደገ"			,
"buyer":	"ዓዳጊ"			,
"buzz":	"ዚዝ በለ"			,
"by all means":	"ብፍጹም"	,
          "cabbage":	"ካውሎ"			,
"cage":	"ጋብያ"			,
"cake":	"ዶልሺ"			,
"calculate":	"ጸብጸበ"			,
"calculation":	"ገምጋም"			,
"calculator":	"መተሓሳሰቢ"			,
"calendar":	"ዓውደ ኣዋርሕ"			,
"calf":	["ምራኽ"	,"ዳንጋ"]		,
"call":	"ጸውዐ"			,
"calm":	["ሃድአ"	,"ህዱእ"]		,
"camel":	"ገመል"			,
"camp":	"መዓስከር"			,
"candle":	"ሽምዓ"			,
"candy":	"ካራመለ"			,
"cane":	"ምርኩስ"			,
"cap":	"ቆቢዕ"			,
"capable":	"ኪኢላ"			,
"capital":	"ርእሲ ከተማ"			,
"captain":	"ካፒታኖ"			,
"car":	"መኪና"			,
"card":	"ካርታ"			,
"card game":	"ጣላዕ"			,
"cardboard":	"ካርቶን"			,
"care":	"ክንከን"			,
"care for":	"ተኸናኸነ"			,
"career":	"መስርሕ ሂወት"			,
"carefully":	"ቀስ"			,
"carefulness":	"ጥንቃቐ"			,
"careless":	"ዘይግደስ"			,
"caretaker":	"ሓላው ርሻን"			,
"carpenter":	"ናሕሲ ዝሰርሕ"			,
"carpet":	"ምንጻፍ"			,
"carriage":	"ባጎኒ"			,
"carrot":	"ካሮት"			,
"carry":	"ተሰከመ"			,
"carry out":	"ኣብ ግብሪ ኣውዓለ"			,
"cart":	"ካሮሳ"			,
"carve":	"ቀረጸ"			,
"case":	"ጉዳይ"			,
"cashier":	"ተሓዝ ገንዘብ"			,
"casing":	"ጋብያ"			,
"castle":	"ኣዳራሽ"			,
"cat":	"ድሙ"			,
"catch":	"ቈለበ"			,
"catch again":	"እንደገና ሓዘ"			,
"caterpillar":	"ኣብ ጨጎራ"			,
"cathedral":	"ቤተ ክርስቲያን"			,
"Catholic":	"ኮተሊኽ"			,
"Catholicism":	"ኩትልኽና"			,
"cauliflower":	["ካውሎ ፍዮሪ"	,"ካውሎ ፊየሪ"]		,
"cause":	["ጠንቂ"	,"ምኽንያት"]		,
"cave":	"በዓቲ"			,
"ceiling":	"ትሕቲ ናሕሲ"			,
"celebrate":	"ኣብዓለ"			,
"celery":	"ሰዴኖ"			,
"cement":	"ቸመንቶ"			,
"cemetery":	"መቓብር"			,
"cent":	"ሳንቲም"			,
"center":	"ማእከል"			,
"centimetre":	"ሰንቲ ሜተረ"			,
"centre of the eye":	["መርዓት"	,"ዓይኒ"]		,
"century":	"ክፍለ ዘመን"			,
"ceremony":	"ጽምብል"			,
"certain":	"ርግጸኛ"			,
"certainly":	"ብርግጽ"			,
"certainty":	"ርግጽነት"			,
"certificate":	"ባጀላ"			,
"certify":	"መስከረ"			,
"chain":	"ሰንሰለት"			,
"chair":	["ሴዳ"	,"መንበር"]		,
"chalk":	"ኩርሽ"			,
"chance":	"ኣጋጣሚ"			,
"change":	"ቀየረ"			,
"channel":	"መትረብ"			,
"chapel":	"ቤተ ጸሎት"			,
"chapter":	"ምዕራፍ"			,
"character":	"ፍሉጥ ሰብ"			,
"charge":	"ጸዓነ"			,
"charity":	"ምጽዋት"			,
"charm":	"ምጥውና"			,
"charming":	"ምጥው"			,
"chase":	"ሃደነ"			,
"chasm":	"ጸድፊ"			,
"chatter":	"ኣዕለለ"			,
"chauffeur":	"ዘዋር መኪና"			,
"cheat":	"ኣታለለ"			,
"check":	"ኣጸረየ"			,
"cheek":	["ኑንጪ"	,"ምዕጉርቲ"	,"ሙዕጉርቲ"]	,
"cheer":	"ኣጨብጨበ"			,
"cheer up":	"ኣተባብዐ"			,
"cheerfulness":	"ሓጎስ"			,
"cheese":	"ፎርማጆ"			,
"chemistry":	"ኬሚስትራ"			,
"cheque":	"ቸክ"			,
"cherish":	"ኣሐንቀቐ"			,
"cherry tree":	"ቸሪ ገረብ"			,
"chest":	"ኣፍ ልቢ"			,
"chest of drawers":	"ኮሞ"			,
"chestnut":	"ፍረ ቸስትናት"			,
"chestnut tree":	"ገረብ ቸስትናት"			,
"chick":	"ጫቚት"			,
"chicken":	["ደርሆ"	,"ጫቚት ደርሆ"]		,
"chicken stew":	["ኣልጫ"	,"ዝግኒ"]		,
"chickpeas":	"ዓተር"			,
"chief":	"ሓለቓ"			,
"child":	"ቈልዓ"			,
"childhood":	"ሕጻንነት"			,
"chilly":	"ቆራሪ"			,
"chimney":	"እቶን"			,
"chimney sweep":	"ጠቐር ዘጽሪ"			,
"chin":	"መንከስ"			,
"chocolate":	"ቸኮላታ"			,
"choice":	"ምርጫ"			,
"choir":	"ጉጅለ ዘመርቲ"			,
"choose":	"መረጸ"			,
"chorus":	"ዜማ"			,
"Christian":	"ክርስትያን"			,
"Christianity":	"ክርስትና"			,
"Christmas":	"ልደት"			,
"church":	"ቤተ ክርስቲያን"			,
"church tower":	"እንዳ ደወል"			,
"cigarette":	"ሽጋራ"			,
"cinema":	"ሲነማ"			,
"circle":	"ክቢ"			,
"circulate":	"ተንቀሳቐሰ"			,
"circulation":	"ምዝዋር"			,
"circumstance":	"ኩነት"			,
"circus":	"ሰርከስ"			,
"citizen":	"ዜጋ"			,
"city dweller":	"ከተመኛ"			,
"civil office":	"ኩነታት መነባብር"			,
"civilization":	"ስልጣኔ"			,
"claim":	"ተጣረዐ"			,
"clang":	"ጫውጫውታ"			,
"clap":	"ኣንጨብጨበ"			,
"clapping":	"ገምታ"			,
"clash":	"ተናጎጸ"			,
"class":	"ክፍሊ"			,
"classical":	"ክላሲካዊ"			,
"classmate":	"መማህርተይ"			,
"classmate ":	"ጓል ክፍሊ"			,
"classmate ":	"ወዲ ክፍሊ"			,
"clatter":	"ጫውጫውታ"			,
"clean":	["ጽሩይ"	,"ንጹር"]		,
"clean out":	"ገዓዘ"			,
"cleanliness":	"ጽሬት"			,
"clear":	"ብሩህ"			,
"clear away":	"ኣጽረየ"			,
"clearly":	"ጽሩይ ውጹእ"			,
"clearness":	"ብራሃን"			,
"clever":	["ንፉዕ"	,"ጎራሕ"]		,
"climate":	["ክሊማ"	,"ንፋስ"]		,
"climb":	"ደየበ"			,
"climb again":	"እንደገና ደየበ"			,
"cling to":	"ጠበቐ"			,
"clinic":	"ክሊኒክ"			,
"cloakroom":	"መቐመጥ ካባ"			,
"clock":	"ሰዓት"			,
"clockmaker":	"ሰራሕ ሰዓት"			,
"close":	"ቀረበ"			,
"close":	"ዓጸወ"			,
"close to":	"ምቅርራብ"			,
"closed":	"ዕጽዉ"			,
"closer":	"ምቅርራብ"		,
"clothes":	"ክዳን"			,
"cloud":	"ደበና"			,
"cloud":	"ጸልመተ"			,
"cloudy":	"ደበናዊ"			,
"clump":	"ድንኩል"			,
"cluster":	"ጎጅለ"			,
"clutter up":	"ኩምራ"			,
"coal":	"ከሰል"			,
"coast":	"ወሰን ባሕሪ"			,
"coat":	"ካቦት"			,
"cocoa":	"ካካው"			,
"code":	"ኮድ"			,
"coffee":	"ቡን"			,
"coffin":	"ሳጹን ሬሳ"			,
"cold":	"ቆራሪ"			,
"colder":	"ዘሓለ"			,
"collapse":	"ዓነወ"			,
"collar":	"ስልማት ክሳድ"			,
"collect":	"ምእካብ"			,
"collection":	["እኩብ"	,"እካበ"]		,
"college":	"ላዕላይ ደረጃ"			,
"collide":	"ተናጎጸ"			,
"colonel":	"ኮሮነል"			,
"colonial":	"መግዛእታዊ"			,
"colonize":	"ግዙእ"			,
"colony":	"ግዝኣት"			,
"colour":	"ሕብሪ"			,
"colourful":	"ሕብራዊ"			,
"colourless":	"ሕብሪ ዘይብሉ"			,
"colt":	"ምሂር"			,
"column":	"ዓንዲ"			,
"comb":	"መመሸጥ"			,
"combine":	"ኣከበ"			,
"come":	"መጸ"			,
"come after":	"ሰዓበ"			,
"come alongside":	"ዓረፈ"			,
"come back":	"እንደገና መጸ"			,
"come down again":	"እንደገና ወረደ"			,
"come from":	"ተለዓለ"			,
"come in":	"ኣተወ"			,
"comedy":	"ኮመዲ"			,
"comfort":	"ቅሳነተ"			,
"comfort":	"ኣጸናንዐ"			,
"comfortable":	"ምቹእ"			,
"command":	"ትእዛዝ"			,
"commanding officer":	"ኮማንደር"			,
"comment upon":	"ገለጸ"			,
"commerce":	"ንግዲ"			,
"commercial":	"ንግዳዊ"			,
"commercial leavened bread":	"ባኒ"			,
"commit":	"ቆጸረ"			,
"committee":	"ኣማኸርቲ"			,
"common":	"ልሙድ"			,
"commune":	"ዞባ"			,
"communication":	"ርክብ"			,
"communion":	"ቁርባን"			,
"companion":	"ካልኣይ"			,
"company":	"ኣሰናይ"			,
"compare":	"ኣመዛዘነ"			,
"comparison":	"ምንጽጻር"			,
"competition":	"ውድድር"			,
"complaint":	"ጥርዓን"			,
"complete":	"ምሉእ"			,
"complicate":	"ኣሕለኽለኸ"			,
"compliment":	"ሞጎስ"			,
"composition":	"ድርሰት"			,
"compost":	"ድኹዒ"			,
"computer":	"ካምፑትር"			,
"conceal":	"ሰተረ"			,
"conceit":	"ትዕቢት"			,
"concern":	"ኣገደሰ"			,
"concert":	"ሙዚቃዊ ምርኢት"			,
"conclude":	"ፈጸመ"			,
"conclusion":	"መደምደምታ"			,
"condemn":	"ኮነነ"			,
"condemnation":	"ኩነና"			,
"condition":	"ኩነታት"			,
"condolence":	"ደበስ"			,
"conduct":	"ኣንፈት ስራሕ"			,
"confederation":	"ፈደረሽን"			,
"conference":	"ኣኼባ"			,
"confess":	"ተኣመነ"			,
"confide":	"ሕድሪ ሃበ"			,
"confidence":	"እምነት"			,
"confirm":	"ኣረጋገጸ"			,
"confirmation":	"ተሃድሶ"			,
"conflict":	"ቃልሲ"			,
"confuse":	"ኣደናገረ"			,
"confused":	"ድንጉር"			,
"confusion":	"ጽልግልግ"			,
"congratulate":	"እንቋዕ ሓጎሰካ በለ"			,
"congress":	"ጉባኤ"			,
"connect":	"ኣላገበ"			,
"connection":	"ፈለጥቲ"			,
"conquer":	"ወረረ"			,
"conquest":	"ማርኾት"			,
"conscience":	"ሕልና"			,
"consent":	"ውዕል"			,
"consent to":	"ኣጽደቐ"			,
"consequence":	"ሳዕቤን"			,
"consider":	"ሓሰበ"			,
"considerable":	"ኣገዳሲ"			,
"consideration":	"ግምት"			,
"consolation":	"ምጽንናዕ"			,
"console":	"ደበሰ"			,
"constable":	"ፖሊስ"			,
"constant":	"ቀዋሚ"			,
"constitute":	"ኣቖመ"			,
"construct":	"ሃነጸ"			,
"construction":	"ህንጻ"			,
"consult":	"ኣማኸረ"			,
"consultation":	"ምይይጥ"			,
"contact":	"ተራኸበ"			,
"contagion":	"ሕማም ምትሕልላፍ"			,
"contain":	"ሓዘ"			,
"contempt":	"ንዕቀት"			,
"content":	"ድሱት"			,
"contents":	"ትሕዝቶ"			,
"continual":	"ቀጻሊ"			,
"continuation":	"መቐጸልታ"			,
"continue":	"ቀጸለ"			,
"continuous":	"ቀጻሊ"			,
"contractor":	"ሰራሕ ገዛ"			,
"contradict":	"ተቓረነ"			,
"contradiction":	"ግርጭት"			,
"contrary":	"ኣንጻር"			,
"contribute":	["ኣብርከተ"	,"ኣበርከተ"]		,
"control":	"ቍጽጽር"			,
"convalescence":	"ጸማልያነት"			,
"convalescent":	"ጸማልያ"			,
"convene":	"ኣላገበ"			,
"convenient":	"ግብራዊ"			,
"convent":	"ገዳም"			,
"convention":	"ዋዕላ"			,
"conversation":	"ዝርርብ"			,
"converse":	"ኣዕለለ"			,
"convert":	"እምነት ኣለወጠ"			,
"convert oneself":	"እምነት ለወጠ"			,
"conviction":	"እምነት"			,
"convince":	"ኣእመነ"			,
"cook":	"ከሸነ"			,
"cooker":	"ፎርነሎ"			,
"cookie":	"ቢስኮቲ"			,
"cooking":	"ክሽነ"			,
"coolness":	"ዛሕሊ"			,
"copper":	"ነሃሲ"			,
"copse":	"ጣሻ"			,
"copy":	"ቅዳሕ"			,
"cordial":	"ልባዊ"			,
"corn":	["ዕፉን"	,"ዑፉን"]		,
"corn bread":	"ሀንዛ"			,
"cornea":	"መርዓት ዓይኒ"			,
"corner":	"ኩርናዕ"			,
"correct":	"ቅኑዕ"			,
"correctly":	"ብትኽክል"			,
"correspond":	"ተራኸበ"			,
"correspondence":	"ርኽክብ"			,
"corridor":	"ኮረደዮ"			,
"cost":	"ዋጋ"			,
"costly":	"ክቡር"			,
"cottage cheese":	"ኣጁቦ"			,
"cotton":	"ጡጥ"			,
"cough":	"ሰዓለ"			,
"coughing":	"ሰዓል"			,
"councillor":	"ኣማኻሪ"			,
"counsel":	"ምኽሪ"			,
"count":	"ቈጸረ"			,
"country":	"ሃገር"			,
"countrymen":	"ሃገራዊ"			,
"countryside":	"ገጠር"			,
"couple":	"ሰብ ሓዳር"			,
"courage":	"ሓቦ"			,
"courageous":	"ተባዕ"			,
"courageously":	"ብትብዓት"			,
"course":	"ኮርስ"			,
"courthouse":	"ቤተ ፍርዲ"			,
"cousin":	"ወዲ ሓትኖ"			,
"cousin":	"ወዲ ሓወቦ"			,
"cousin":	"ወዲ ኣሞ"			,
"cousin":	"ወዲ ኣኮ"			,
"cover":	"ከደነ"			,
"cover oneself up":	"ተጎልበበ"			,
"cover up":	"ጎልበበ"			,
"coverage":	"መኽደኒ"			,
"cow":	"ላም"			,
"cowshed":	"ደምበ"			,
"cradle":	"ዓራት ሕጻን"			,
"craft":	"ናይ ስራሕ ክእለት"			,
"crane":	"ሰፍሳፊት"			,
"crawl":	"ለመመ"			,
"crazy":	"ጽልልቲ"			,
"crazy person":	"ጽሉል"			,
"cream":	"ቅብኣት"			,
"create":	"መሃዘ"			,
"creator":	"ፈጣሪ"			,
"creditor":	"ኣዋዲ"			,
"cricket":	"ዕንጭራር"			,
"crime":	"ገበን"			,
"criminal":	"ገበነኛ"			,
"criticize":	"ነቐፈ"			,
"cross":	"መስቀል"			,
"cross":	["ተሳገረ"	,"ሰገረ"]		,
"crossroads":	"መስቀላዊ መንገዲ"			,
"crowd":	"ጽቕጥቅጥ"			,
"crown":	"ኣኽሊል"			,
"crowning":	"ድፍኣተ ዘውዲ"			,
"cruel":	"ሕሱም"			,
"cruelty":	"ጭካነ"			,
"crumb":	"ርፍራፍ"			,
"crush":	"ጨፍለቐ"			,
"cry":	"ብኽያት"			,
"crystal":	"ሓቒቕ"			,
"cult":	"እምነት"			,
"cultivate":	"ኮስኮሰ"			,
"cultivated":	"ኩስኩስ"			,
"cultivation":	"ዘራእቲ"			,
"cunning":	["ሃሳይ"	,"ጎራሕ"]		,
"cup":	"ኩባያ"			,
"cupboard":	"ኣርማድዮ"			,
"cure":	"ፈውሲ"			,
"curiosity":	"ህንጥይና"			,
"curious":	"ህንጡይ"			,
"curly":	"ኮርዳድ ጸጉሪ"			,
"current":	"ህሉው"			,
"currently":	"ኣብዚ ግዜ ዚ"			,
"curse":	"ረገመ"			,
"curtain":	"መጋረጀ"			,
"curved":	"ጥዉይ"			,
"cushion":	"መተርኣስ"			,
"custom":	"ልምዲ"			,
"customer":	"ዓሚል"			,
"cut":	"ቈረጸ"			,
"cut out":	"ከምከመ"			,
"cut short":	"ኣሕጸረ"			,
"cyclist":	"ዘዋር ብሽክለታ"	,
          "daily":	"መዓልታዊ"			,
"dairy":	"እንዳ ጸባ"			,
"dam":	"ግድብ"			,
"damage":	"ጉድኣት"			,
"dance":	"ሳዕስዒት"			,
"dancing":	"ሳዕስዒት"			,
"danger":	"ሓደጋ"			,
"dangerous":	"ሓደገኛ"			,
"dare to do":	"ደፈረ"			,
"dark":	"ጸልማት"			,
"darken":	"ጸልመተ"			,
"darn":	"ኣዐረየ"			,
"date":	["ቆጸራ"	,"ተምሪ"]		,
"dates":	"ተምሪ"			,
"daughter":	"ጓል"			,
"dawn":	"ወጋሕታ"			,
"day":	"መዓልቲ"			,
"daytime":	"መዓልቲ"			,
"dead":	"ምዉት"			,
"dead body":	"ሬሳ"			,
"deadline":	"ድንጓየ"			,
"deafness":	"ጸማምነት"			,
"dear":	"ክቡር"			,
"death":	"ሞት"			,
"debate":	"ተኻተዐ"			,
"debris":	"ርፍራፍ"			,
"debt":	"ዕዳ"			,
"debtor":	"ተኣዋዲ"			,
"decease":	"ሞተ"			,
"deceased":	"ምዉት"			,
"deceive":	"ከድዐ"			,
"December":	"ታሕሳስ"			,
"decent":	"ሓቀኛ"			,
"decide":	"ወሰነ"			,
"decision":	"ውሳኔ"			,
"deck":	"መዓሸግ ባብር"			,
"declaration":	"ኣዋጅ"			,
"declare":	"ኣወጀ"			,
"decline":	"ነጸገ"			,
"decorate":	"ሰለመ"			,
"decoration":	"ስልማት"			,
"decorative":	"ስልማታዊ"			,
"decrease":	"ኣንኣሰ"			,
"dedicate":	"ወፈየ"			,
"deed":	"ተግባር"			,
"deep":	"ዓሚቝ"			,
"deer":	"ዓጋዜን"			,
"defeat":	"ስዕረት"			,
"defeated person":	"ስዑር"			,
"defect":	"ጉድለት"			,
"defence":	"ምክልኻል"			,
"defend":	"ተኸላኸለ"			,
"defender":	"ተኸላኻሊ"			,
"deforest":	"ኣበደመ"			,
"degree":	"ደረጃ"			,
"delay":	"ደንጎየ"			,
"delicate":	"ተነቃፊ"			,
"delicious":	"ምቁር"			,
"delight":	"ፍስሃ"			,
"delighted" :	"ተሓጎሰ"			,
"deliver":	"ኣብጽሐ"			,
"delivery":	"ዕደላ"			,
"delivery man":	"ኣባጻጽሒ"			,
"delusion":	"ጽላለ"			,
"demand":	"ሓተተ"			,
"demolish":	"ኣፍራሰ"			,
"den":	"በዓቲ"			,
"deny":	"ኣሉ በለ"			,
"departing ticket":	"ቲከት መኸዲ"			,
"departure":	["ብገሳ"	,"ተበገሶ"]		,
"depend on":	"ተመርኮሰ"			,
"deprivation":	"እገዳ"			,
"deprive":	"ኣገደ"			,
"deputy":	"ወኪል ህዝቢ"			,
"describe":	"ገለጸ"			,
"description":	"መግለጺ"			,
"desert":	"ምድረ በዳ"			,
"deserve":	"ተገበአ"			,
"deserving":	"ብቑዕ"			,
"design":	"ሰኣለ"			,
"designer":	"ሰኣሊ"			,
"desire":	"ድሌት"			,
"desire":	"ደለየ"			,
"desk":	"ጠረጰዛ"			,
"desperate":	"ተስፋ ዝቖረጸ"			,
"desperation":	"ቅብጸተ ተስፋ"			,
"despise":	"ነዓቐ"			,
"destiny":	"ጽሕፍቶ"			,
"destroy":	"ኣዕነወ"			,
"detach":	"ፈተሐ"			,
"determination":	"ውሳኔ"			,
"determined":	"ነቓጽ"			,
"detest":	"ጸልአ"			,
"devastate":	"ዕንወት"			,
"develop":	"ማዕበለ"			,
"development":	"ምዕባለ"			,
"devil":	"ሰይጣን"			,
"devotion":	"ውፉይነት"			,
"dew":	"ዛዕዛዕታ"			,
"diamond":	"ኣልማዝ"			,
"dictionary":	"መዝገበ ቃላት"			,
"die":	"ሞተ"			,
"difference":	"ፍልልይ"			,
"different":	"ዝተፈልየ"			,
"difficult":	"ብርቱዕ"			,
"difficulty":	"ሽግር"			,
"dig":	"ፈሓረ"			,
"digestive system":	"ከብዲ"			,
"dim":	"ሃሳስ"			,
"diminish":	"ኣንኣሰ"			,
"dining room":	"መመገቢ ክፍሊ"			,
"dinner":	"ድራር"			,
"diplomatic":	"ፖለቲካዊ"			,
"direct":	"ቀጥታ"			,
"director":	"ሓላፊ"			,
"dirt":	"ጭቃ"			,
"dirty":	["ጭቃዊ"	,"ረሳሕ"]		,
"disadvantage":	"ጉድኣት"			,
"disappear":	["ጠፍአ"	,"ሃለዋት ኣጥፈአ"]		,
"disappearance":	"ጥፍኣት"			,
"disappointment":	"ጓሂ"			,
"disastrous":	"ሓደገኛ"			,
"discharge":	"ኣሰናበተ"			,
"disciple":	"ሰዓቢ"			,
"discipline":	"ስነ ስርዓት"			,
"disclose":	"ቀልዐ"			,
"discomfort":	"ዘይጥጣሐ"			,
"discord":	"ጽልግልግ"			,
"discourage":	"ተስፋ ዝቖረጸ"			,
"discover":	"ረኸበ"			,
"discrimination":	"ፍሉይነት"			,
"discuss":	"ተዛተየ"			,
"discussion":	"ክትዐ"			,
"disease":	"ሕማም"			,
"disgrace":	"ሕፍረት"			,
"dishes":	"ኣቑሑ መግቢ"			,
"dismiss":	"ኣሰነበተ"			,
"disobedience":	"ዘይምእዛዝ"			,
"disobedient":	"ዘይምቕሉል"			,
"disobey":	"ዘይምእዛዝ"			,
"disorder":	"ፋሕ ዝበለ"			,
"dispatch":	"ሰደደ"			,
"displace":	"ቦታ ቀየረ"			,
"display":	"ምርኢት"			,
"display":	"ኣቕረበ"			,
"displeased":	"ዘይሕጉስ"			,
"dissolve":	"ሓቐቐ"			,
"distance":	"ርሕቀት"			,
"distant":	"ርሑቕ"			,
"distinction":	"ፍሉይነት"			,
"distract":	"ኣዘናገዐ"			,
"distribute":	"ዓደለ"			,
"distribution":	"ዕደላ"			,
"district":	"ኣከባቢ"			,
"distrust":	"ጥርጣረ"			,
"disturb":	"ሃወኸ"			,
"ditch":	"ጉድጓድ"			,
"dive":	"ተደርገመ"			,
"divert":	"ጠወየ"			,
"divide up":	"መቐለ"			,
"division":	"ምምቃል"			,
"divorce":	"ተፋትሐ ሓዳር"			,
"divorced":	"ዝተፋትሐ"			,
"do":	"ገበረ"			,
"do away with":	"ኣጥፈአ"			,
"do one's best":	"ጸዓረ"			,
"do someone’s hair":	"ዘርገፈ"			,
"docile":	"ምእዙዝ"			,
"doctor":	"ሓኪም"			,
"dog":	"ከልቢ"			,
"dog house":	"ገዛ ኸልቢ"			,
"doll":	"ባምቡላ"			,
"dominate":	"ተቖጻጸረ"			,
"donkey":	"ኣድጊ"			,
"door":	"ማዕጾ"			,
"doorstep":	"ደርኩኺት"			,
"double":	"ዕጽፊ"			,
"double":	"ደረበ"			,
"doubt":	"ጥርጥር"			,
"doubt":	"ተጠራጠረ"			,
"dough":	"ቢሑቕ"			,
"down take":	"ደምሰሰ"		,
"dozen":	"ደርዘን"			,
"dragon fly":	"ፈረሰኛ"			,
"drain":	"ጸንቀቐ"			,
"drama":	"ድራማ"			,
"dramatic":	"ድራማዊ"			,
"draw":	["ኣንሰሓበ"	,"ሰኣለ"]		,
"draw oneself up":	"ቀንዐ"			,
"draw up":	"ነደፈ"			,
"draw water":	"ገለለ"			,
"drawer":	"ተመዛዚ"			,
"drawing":	"ስእሊ"			,
"dream":	"ሕልሚ"			,
"dream":	"ሓለመ"			,
"dress":	"ጀለብያ"			,
"dress":	"ለበሰ"			,
"dressing":	"ኣተሓኻኸማ"			,
"dressmaker":	"ሰፋይ ክዳን"			,
"dried":	"ንቑጽ"			,
"drink":	"መሰተ"			,
"drive":	"ዘወረ"			,
"driver":	"መራሕ መኪና"			,
"drop":	"ንጣብ"			,
"drop":	"ወደቐ"			,
"drought":	"ድርቂ"			,
"drown":	"ጠሓለ"			,
"drowned":	"ጠሓለ"			,
"drum":	"ኮቦሮ"			,
"drunk":	"ሰኽራም"			,
"dry":	"ንቑጽ"			,
"dry":	"ኣንቀጸ"			,
"dryness":	"ድርቂ"			,
"duck":	"ደርሆ ማይ"			,
"dull":	"ጎዲም"			,
"dust":	"ዶሮና"			,
"duty":	"ጉቡእ"			,
"dwarf":	"ድንኪ"			,
"dying":	"መዋቲ"			,
"ear":	"እዝኒ"			,
"early":	"ናይ ንጉሆ"			,
"early":	"ብቑልጡፍ"			,
"ease":	"ቅሳነተ"			,
"easily":	"ብቐሊል"			,
"easiness":	"ቅሊ"			,
"east":	"ምብራቅ"			,
"Easter":	"ፋሲካ"			,
"easterly":	"ምብራቅ"			,
"eat":	"በልዐ"			,
"echo":	"መቓልሕ"			,
"echo":	"መቓልሕ ሃበ"			,
"economics":	"ዕቃበ"			,
"economize":	"ቆጠበ"			,
"economy":	"ዕቃበ"			,
"edge":	"ወሰን ወሰን"			,
"editor":	"ደራሲ"			,
"educate":	"መሃረ"			,
"education":	"ትምህርቲ"			,
"effect":	["ሳዕቤን"	,"ውጽኢት"]		,
"effect":	"ሳዕቤን"			,
"effort":	"ጻዕሪ"			,
"egg":	"እንቋቑሖ"			,
"egoism":	"ስስዐ"			,
"eight":	"ሸሞንተ"			,
"eighteen":	"ዓሰርተ ሸሞንተ"			,
"eighth grade":	"ሻሙናይ ክፍሊ"			,
"eighty":	"ሰማንያ"			,
"elbow":	"ኩርናዕ ኢድ"			,
"eldest":	"ቦኹሪ"			,
"elect":	"መረጸ"			,
"electrical":	"ኤለትሪካዊ"			,
"electricity":	"ኤለትሪክ"			,
"elegant":	"ምልኩዕ"			,
"elementary school":	"መባእታ ደረጃ"			,
"elephant":	"ሓርማዝ"			,
"eleven":	"ዓሰርተ ሓደ"			,
"eleventh grade":	"ዓሰርተ ሓደ ክፍሊ"			,
"elsewhere":	"ኣብ ካልእ ቦታ"			,
"empire":	"ንግስነት"			,
"employ":	"ኣስረሐ"			,
"employer":	"ዋሃብ ስራሕ"			,
"employment":	"ስራሕ"			,
"empty":	"ጥርሑ"			,
"encircle":	"ኣኽበበ"			,
"encourage":	"ኣተባብዐ"			,
"end":	"መወዳእታ"			,
"end":	"ኣቋረጸ"			,
"enemy":	"ጸላኢ"			,
"energetic":	"ጻዕረኛ"			,
"energy":	"ሓይሊ"			,
"engaged to":	"ተሓጸየ"			,
"engagement":	"ሕጸ"			,
"engine":	"ሞተር"			,
"engineer":	"መሃንድስ"			,
"English":	"እንግሊዛዊ"			,
"English":	"እንግሊዘኛ"			,
"engrave":	"ቀረጸ"			,
"engraving":	"ቅርጺ"			,
"enjoy":	"ደስ በሎ"			,
"enlarge":	"ኣዕበየ"			,
"enormous":	"ግዙፍ"			,
"enough":	"እኹል"			,
"enough":	"ኣኸለ"			,
"ensure":	"ኣረጋገጸ"			,
"enter":	"ኣተወ"			,
"enterprise":	"ወኒነ ትካል"			,
"entertain":	"ኣዘናገዐ"			,
"entirely":	"ብምሉኡ"			,
"entrance":	"መእተዊ ክፍሊ"			,
"envelope":	"ሰታሪት"			,
"equal":	"ማዕረ"			,
"equally":	"ከምኡውን"			,
"equip":	"ኣዕጠቐ"			,
"equipment":	"መሳርሒ"			,
"eraser":	"መደምሰስ"			,
"erect":	"ኣቕነዐ"			,
"error":	"ጌጋ"			,
"escape":	"መለቐ"			,
"especially":	"ብፍላይ"			,
"essay":	"ፈተነ"			,
"essential":	"ግድነታዊ"			,
"establish":	"መሰረተ"			,
"estimate":	"ግምት"			,
"estimate":	"ግምት"			,
"eternal":	"ዘላኣለማዊ"			,
"eternity":	"ዘላኣለም"			,
"evacuate":	"ኣግዓዘ"			,
"even":	"ጽምዲ ቁጽሪ"			,
"evening":	"ምሸት"			,
"event":	"ፍጻሜ"			,
"ever":	"ብፍጹም"			,
"everyday":	"መዓልታዊ"			,
"everywhere":	"ኣብ ኩኡ ቦታ"			,
"evidence":	"መረጋገጺ"			,
"evidence":	"መስከረ"			,
"exact":	"ልክዕ"			,
"exaggerate":	"ኣጋነነ"			,
"exam":	"ምርመራ"			,
"examine":	"መርመረ"			,
"example":	"ኣብነት"			,
"exception":	"ፍሉይነት"			,
"exceptional":	"ፍሉይ"			,
"exchange":	"ልውውጥ"			,
"exchange":	"ተለዋወጠ"			,
"excitement":	"ምቕስቃስ"			,
"exclamation":	"ቃል ኣጋንኖ"			,
"excuse":	"ምኽኒት"			,
"excuse":	"ይቕረ በለ"			,
"exercise":	"ልምምድ"			,
"exhaust":	"ኣድከመ"			,
"exhibit":	"ዘርገሐ"			,
"exhibition":	"ምርኢት"			,
"exist":	"ሃለወ"			,
"existence":	"ህላዌ"			,
"exit":	"መውጽኢ"			,
"expand":	"ኣሰፍሐ"			,
"expect":	"ተጸበየ"			,
"expense":	"ወጻኢ"			,
"expensive":	"ክቡር"			,
"experience":	"ፈለጠ"			,
"experienced":	"ፍሉጥ"			,
"expire":	"ወደቐ"			,
"explain":	"ኣረድአ"			,
"explanation":	"መግለጺ"			,
"explode":	"ነቶገ"			,
"express":	"ገለጸ"			,
"express train":	"ቅልጡፍ ባቡር"			,
"extend":	"ኣናውሐ"			,
"extraordinary":	"ፍሉይ"			,
"eye":	"ዓይኒ"			,
"eyebrow":	"ሸፋሽፍቲ ዓይኒ"			,
"eyelash":	"ቅርኒብ ዓይኒ"			,
"eyelid":	"ኮቦሮ ዓይኒ"			,
          "fabric":	"ዓለባ"			,
"face":	"ገጽ"			,
"face to face":	"ገጽ ንገጽ"			,
"facilitate":	"ኣቕለለ"			,
"factory":	"ቤተ ዕዮ"			,
"faded":	"ሃሳስ"			,
"fail":	["ፈሸለ"	,"ምውዳቕ"	,"ምትራፍ"]	,
"failed":	["ወዲቐ"	,"ተሪፈ"]		,
"failure":	"ፍሽለት"			,
"faith":	"እምነት"			,
"faithful":	"እሙን"			,
"fall":	"ውድቀት"			,
"fall":	"ወደቐ"			,
"fall again":	"እንደገና ወደቐ"			,
"fall asleep":	"ደቀሰ"			,
"fall back":	"ደሓረ"			,
"family":	"ቤተ ሰባዊ"			,
"family":	"ስድራ ቤት"			,
"famous":	"ውሩይ"			,
"fantasy":	"ባህጊ"			,
"far":	"ርሑቕ"			,
"farewell":	"ደሓን ኩን"			,
"farm":	"ናይ ሕርሻ ገዛ"			,
"farmer":	"ሓረስታይ"			,
"fashion":	"ቅዲ ሞዳ"			,
"fast":	"ቅልጡፍ"			,
"fasten":	"ኣሰረ"			,
"fat":	"ስቡሕ"			,
"father":	"ኣቦ"			,
"fatigue":	"ድኹም"			,
"fault":	"ጌጋ"			,
"favourite":	"ፍትው"			,
"fear":	"ፍርሒ"			,
"fear":	"ፈርሐ"			,
"feast":	"በዓል"			,
"feather":	"ክንቲት"			,
"February":	"ለካቲት"			,
"feed":	"ኣብልዐ"			,
"feel sorry":	"ደንገጸ"			,
"female":	"ኣንስተይቲ"			,
"female director":	"ሓላፊት"			,
"female guard":	"ሓላዊት"			,
"feminine":	"ኣንስታይ"			,
"fence":	"ተኽሊ ሓጹር"			,
"fertile":	"ፈራይ"			,
"fertilizer":	"ድኹዒ"			,
"festival":	"በዓል"			,
"fever":	"ረስኒ"			,
"feverish":	"ርሱን"			,
"fiancé":	"ሕጹይ"			,
"fiancée":	"ሕጺቲ"			,
"field":	"ጎልጉል"			,
"fifteen":	"ዓሰርተ ሓሙሽተ"			,
"fifth grade":	"ሓሙሻይ ክፍሊ"			,
"fifty":	"ሓምሳ"			,
"fight":	"ቃልሲ"			,
"fighter":	"ተጋዳላይ"			,
"figure":	"ቅርጺ"			,
"fill up":	"መለአ"			,
"film":	"ፊልም"			,
"finally":	["መወዳእትኢ"	,"ኣብ"]		,
"finance":	"ፊናንስ"			,
"find":	"ረከበ"			,
"fine":	"መቕጻዕቲ"			,
"finger":	"ኣጻብዕ"			,
"finger nail":	"ጽፍሪ"			,
"finger nails":	"ጽፍሪ ኢድ"			,
"fingers":	"አጻብዕቲ ኢድ"			,
"finish":	"ወደአ"			,
"fire":	"ሓዊ"			,
"fireman":	"መጠፈኢ ሓዊ"			,
"firmly":	"ጽኑዕ"			,
"first":	"ቀዳማይ"			,
"first grade":	"ቀዳማይ ክፍሊ"			,
"first name":	"ስም"			,
"fish":	"ዓሳ"			,
"fish for":	"ገፈፈ"			,
"fisher":	"ገፋፍ ዓሳ"			,
"fishhook":	"መቑለብ ዓሳ"			,
"fist":	"ዕምኮ"			,
"fit":	"ተጋጠመ"			,
"five":	"ሓሙሽተ"			,
"fix":	"ኣዐረየ"			,
"flag":	"ባንደራ"			,
"flake":	"ቅርፍቲ"			,
"flame":	"ሃልሃልታ"			,
"flat":	"ጸፊሕ"			,
"flatten":	"ኣጽፈሐ"			,
"flesh":	"ስጋ"			,
"flexibility":	"ተዓጻጻፍነት"			,
"flexible":	"ተዓጻጻፊ"			,
"flight":	"ንፍረት"			,
"float":	"ተንስፈፈ"			,
"flood":	"ኣጥለቕለቐ"			,
"flour":	"ሓሪጭ"			,
"flow":	"ፈሰሰ"			,
"flower":	"ዕምባባ"			,
"flower":	"ዓምበበ"			,
"flu":	"ኡንፍልወንዛ"			,
"flute":	"ሻምብቆ"			,
"fly":	"ሃመማ"			,
"fly away":	"ነፈረ"			,
"flying":	"ንፍረት"			,
"fog":	"ግመ"			,
"foggy":	"ግማዊ"			,
"fold":	"ዕጻፍ"			,
"fold":	"ዓጸፈ"			,
"folk":	"ሰባት"			,
"follow":	"ሰዓበ"			,
"following":	"ዝስዕብ"			,
"food":	"መግቢ"			,
"foolish":	"ዓሻ"			,
"foot":	"እግሪ"			,
"football":	"ኩእሶ እግሪ"			,
"footstep":	"ስጉምቲ"			,
"forbid":	"ወገደ"			,
"force":	"ሓይሊ"			,
"forehead":	"ግንባር"			,
"foreign":	"ባእዳዊ"			,
"foreigner":	"ወጻእተኛ"			,
"forest":	"ጫካ"			,
"foretell":	"ኣፍለጠ"			,
"forget":	"ረሰዐ"			,
"forgetfulness":	"ርሳዐ"			,
"forgive":	"ይቕረ በለ"			,
"fork":	"ፋርከታ"			,
"form":	"ቅርጺ"			,
"formality":	"ጽምብል"			,
"formation":	"ኣቀራርጻ"			,
"formerly":	"ኣብ ሕሉፍ እዋናት"			,
"fortune":	"ዕድል"			,
"forty":	"ኣርባዓ"			,
"forward":	"ሰደደ"			,
"found":	"ሰረተ"			,
"fountain":	"ፈልፋሊ"			,
"four":	"ኣርባዕተ"			,
"fourteen":	"ዓሰርተ ኣርባዕተ"			,
"fourth grade":	"ራብዓይ ክፍሊ"			,
"fox":	"ወኻርያ"			,
"fragile":	"ተሰባሪ"			,
"fragrance":	"ሽታ ፈረንጂ"			,
"frankly":	"ብቕንዕና"			,
"frankness":	"ቅንዕና"			,
"free":	"ነጻ"			,
"freedom":	"ሓርነት"			,
"French":	"ፈረንሳዊ"			,
"frequent":	"ተደጋጋሚ"			,
"frequent":	"ኣዘውተረ"			,
"frequently":	"ብዝተደጋገመ"			,
"fresh":	"ሓዲሽ"			,
"Friday":	"ዓርቢ"			,
"friend":	"ዓርኪ"			,
"friendly":	"ዕርክነታዊ"			,
"friendship":	"ዕርክነት"			,
"frightening":	"ኣፍራሒ"			,
"frog":	"እንቁሮያብ"			,
"front":	"ቅድሚት"			,
"front of":	"ቅድም"			,
"front":	"ብቕድሚ"			,
"frost":	"ኣስሓይታ"			,
"fruit":	"ፍረ"			,
"fruit tree":	"ተኽሊ ፍረ"			,
"frying":	"ቅልዋ"			,
"fuel":	"ነዳዲ"			,
"fulfill":	"ሰመረ"			,
"full":	"ምሉእ"			,
"fun have":	"ተዘናገዐ"			,
"function":	"ኣገልገለ"			,
"fund":	"እኩብ ገንዘብ"			,
"fund":	"ሰረተ"			,
"funeral":	"ቀብራዊ"			,
"funny":	"መስሓቕ"			,
"furious":	"ሓራቖ"			,
"furnace":	"ፎርነሎ"			,
"furniture":	"ኣቕሓ ገዛ"			,
"future":	"መጻኢ"			,
"gain":	"ረብሓ"			,
"gallery":	"ኣዳራሽ"			,
"game":	"ጸወታ"			,
"game of chance":	"ምጥላዕ"			,
"gangster":	"ሽፍታ"			,
"garden":	"ጀርዲን"			,
"garlic":	"ሽጉርቲ ጻዕዳ"			,
"gas":	"ጋዝ"			,
"gasoline":	"በንዚን"			,
"gather":	"ኣከበ"			,
"gather honey":	"ማዓር ኣከበ"			,
"gathering":	"ኣኼባ"			,
"general":	"ሓፈሻዊ"			,
"general":	"ጀነራል"			,
"generosity":	"ልውህና"			,
"generous":	"ለጋስ"			,
"genius":	"ኣስተውዓሊ"			,
"gentleness":	"ሕያውነት"			,
"gently":	"ቀስ"			,
"geography":	"ጆግራፍ"			,
"geometrician":	"ጆመትሪ"			,
"German":	"ጅርመናዊ"			,
"get":	"ረኸበ"			,
"get around":	"ሓለፈ"			,
"get used to":	"ለመደ"			,
"get used to someone":	"ኣልመደ"			,
"gift":	"ህያብ"			,
"giraffe":	"ዘራፍ"			,
"girl":	"ጓል"			,
"girlhood":	"ንእስነት"			,
"give":	"ሃበ"			,
"give an airing":	"ኣናፈሰ"			,
"give back":	"መለሰ"			,
"gladly":	"ደስታ"			,
"glass":	"ብርጭቆ"			,
"gleam":	"ኣንጸባረቐ"			,
"glide":	"ኣንሻተተ"			,
"gloomy":	"ትኩዝ"			,
"glove":	"ግዋንቲ"			,
"glue":	"ኮላ"			,
"glue":	"ለጠፈ"			,
"gnash":	"ፋሕፈሐ"			,
"go":	"ከደ"			,
"go away":	"ረሓቐ"			,
"go beyond":	"ቀደመ"			,
"goal":	"ዕላማ"			,
"goat":	"ጢል"			,
"God":	"እግዚኣብሄር"			,
"godchild":	"ጓል ብልግና"			,
"godfather":	"ኣባሊገ"			,
"godmother":	"ኣባሊገ"			,
"godson":	"ወዲ ብልግና"			,
"goggles":	"መነጸር"			,
"gold":	"ወርቂ"			,
"good":	"ጽቡቕ"			,
"good evening":	"ከመይ ኣምሲኩም"			,
"good looking":	"ምልኩዕ"			,
"good morning":	"ደሓንዶ ሓዲርካ"			,
"goodbye":	"ደሓን ኩን"			,
"goodnight":	"ደሓን ሕደር"			,
"goods":	"ኣቕሓ"			,
"goodwill":	"ጽቡቕ ድሌት"			,
"gossip":	"ኣዕለለ"			,
"government":	"መንግስቲ"			,
"grace":	"ምሕረት"			,
"grade":	"ነጥቢ"			,
"graduate":	"ምምራቕ"			,
"graduated":	"ተመሪቐ"			,
"grain":	"እኽሊ"			,
"gram":	"ግራም"			,
"grammar":	"ስዋስዉ"			,
"granary":	"መኽዘን ኽፍሊ"			,
"grand father":	"ኣቦሓጎ"			,
"grand mother":	"ዓባይ"			,
"granddaughter":	"ጓል ጓል"			,
"granddaughter":	"ጓል ወዲ"			,
"grandson ":	"ወዲ ጓል"			,
"grandson":	"ወዲ ወዲ"			,
"grant":	"ኣፍቀደ"			,
"grape":	"ወይኒ"			,
"grasp":	["ጸቐጠ"	,"ተረድአ"]		,
"grass":	"ሳዕሪ"			,
"grasshopper":	"ጢል ኣደይ ማርያም"			,
"grateful":	"ኣመስጋኒ"			,
"gratitude":	"ምስጋና"			,
"grave":	"መቓብር"			,
"grazing":	"ሳዕሪ ምብላዕ"			,
"grease":	"ስብሒ"			,
"great":	["ዓብዪ"	,"ዓብይ"]		,
"greatly":	"ብብዚሒ"			,
"green":	"ቀጠልያ"			,
"green beans":	"ፋጆሊ"			,
"green cabbage":	"ካውሎ"			,
"green collards":	"ሓምሊ"			,
"green mustard":	"ሐምሊ ኣድሪ"			,
"green onion":	"ዝቢኢ ሹጉርቲ"			,
"green pepper":	"ጉዕ"			,
"greenery":	"ለምዒ"			,
"greet":	"ተቐበለ"			,
"greeting":	"ሰላምታ"			,
"grey":	"ሓሙኹሽታይ"			,
"grief":	"ሓዘን"			,
"grilled meat":	"ጥብሲ"			,
"grind":	"ጠሓነ"			,
"grip":	"ምሓዝ"			,
"grocer":	"በዓል ድኳን"			,
"grocery":	"ድኳን"			,
"ground":	"ምድሪ"			,
"group":	"ጉጅለ"			,
"group":	"ጎጅለ"			,
"grow":	"ዓበየ"			,
"grow old":	"ኣረገ"			,
"growl":	"ኣዕዘምዘመ"			,
"grumble":	"ኣጉረምረመ"			,
"guarantee":	"ውሕስነት"			,
"guarantee":	"ተዋሓሰ"			,
"guard":	["ሓላዊ"	,"ዘብዐኛ"]		,
"guess":	"ገመተ"			,
"guide":	"መራሒ"			,
"guilt":	"ገበን"			,
"guilty":	"በደለኛ"			,
"guilty":	"ገበነኛ"			,
"gums":	"ግርጻን"			,
"gun":	"ጠበንጃ"			,
"gymnastics":	"ምውስዋስ አካላት"			,
"habit":	"ኣመል"			,
"hail":	"ኣጨብጨበ"			,
"hair":	["ጽምሪ"	,"ጨጉሪ"]		,
"hairdresser":	"ቀምቃሚ"			,
"half":	"ፍርቂ"			,
"half year":	"መንፈቕ"			,
"hammer":	"ማርተሎ"			,
"hand":	"ኢድ"			,
"hand bell":	"ቃጭል"			,
"hand writing":	"ጽሕፈት"			,
"handful":	"ዕታሮ"			,
"handkerchief":	"መንዲል"			,
"handshake":	"ሰላምታ ኢድ"			,
"hang up":	"ኣንጠልጠለ"			,
"happen":	"ኮነ"			,
"happiness":	"ታሕጓስ"			,
"happy":	"ሕጉስ"			,
"hard":	"ድሩቕ"			,
"hare":	"ማንቲለ በረኻ"			,
"harm":	"ጉድለት"			,
"harmful":	"ተጓዳኢ"			,
"harmless":	"ዘይጎድእ"			,
"harmony":	"ስምምዕ"			,
"harvest":	"ቀውዒ"			,
"harvest":	"ቀውዐ"			,
"harvest grapes":	"ወይኒ ኣረየ"			,
"hat":	"ቆቢዕ"			,
"hate":	"ጸልአ"			,
"hay":	"ሓሰር"			,
"hazy":	"ግማዊ"			,
"he":	"ንሱ"			,
"head":	["ኣስራሒት"	,"ርእሲ"]		,
"head":	"ኣስራሒ"			,
"head master":	["ዳይረክቶር"	,"አማሓዳሪ"]		,
"healing":	"ምሕዋይ"			,
"health":	"ጥዕና"			,
"healthy":	"ጥዑይ"			,
"hear":	"ሰመዐ"			,
"hearing":	"ምስማዕ"			,
"heart":	"ልቢ"			,
"heat":	"ዋዒ"			,
"heat":	"ኣውዓየ"			,
"heater":	"መሞቒ"			,
"heating":	"መውዓይ"			,
"heavenly":	"ገነታዊ"			,
"heavy":	"ከቢድ"			,
"heel":	["ታኮ"	,"ሸኾና እግሪ"]		,
"heels":	"ኩሩኹሮ"			,
"height":	"ቁመት"			,
"hello":	"ሰላም"			,
"helmet":	"ቆቢዕ ወታሃደር"			,
"help":	"ሓገዝ"			,
"help":	"ሓገዘ"			,
"henhouse":	"መራብሒ ደርሁ"			,
"here":	"ኣብዚ"			,
"hero":	"ቀንዲ ተዋሳኢ"			,
"heroic":	"ጀግና"			,
"hers":	"ናታ"			,
"hesitate":	"ተጠራጠረ"			,
"hesitation":	"ጥርጠራ"			,
"hide":	"ሐብአ"			,
"hiding place":	"መሕብኢ"			,
"high school":	"ካልኣይ ደረጃ"			,
"higher":	"ላዕላይ"			,
"hill":	"ኩርባ"			,
"hip":	"ምሕኩልቲ"			,
"hips":	"ጎሎ"			,
"hire":	"ኣካረየ"			,
"his":	"ናቱ"			,
"history":	"ታሪኽ"			,
"hit":	"ወቕዐ"			,
"hobo":	"ኮብላሊ"			,
"hold":	"ምሓዝ"			,
"hold":	"ሓዘ"			,
"hold up":	"ደንጎየ"			,
"hole":	"ነኳል"			,
"hole":	"ጉድጓድ"			,
"holiday":	"በዓል"			,
"holy":	"ቅዲስ"			,
"holy":	"ጻድቕ"			,
"home":	"ገዛ"			,
"homeland":	"ዓደቦ"			,
"homeless":	"ኮብላሊ"			,
"homemade leavened bread":	"ሕንባሻ"			,
"honest":	"ሓቀኛ"			,
"honesty":	"ቅንዕና"			,
"honey":	"ማዓር"			,
"honey wine":	"ሜስ"			,
"honour":	"ኣኽበረ"			,
"honourable":	"ክቡር"			,
"hope":	"ተስፋ"			,
"hope for":	"ተተስፈየ"			,
"horizontal":	"ግድሞ"			,
"horn":	"ቀርኒ"			,
"horrible":	"ኣሰንባዲ"			,
"horse":	"ፈረስ"			,
"horse rider":	"ፈረሰኛ"			,
"horsemanship":	"ፈረስ ምስቃል"			,
"hose":	"ቱቦ"			,
"hospitable":	"ኣአንጋዲ"			,
"hospital":	"ሆስፒታል"			,
"host":	"ተቐባል ጋሻ"			,
"hot":	"ውዑይ"			,
"hotel":	"ሆቴል"			,
"hour":	"ሰዓት"			,
"house":	"ገዛ"			,
"how":	"ከመይ"			,
"how much":	"ክንደይ"			,
"however":	["ግን"	,"ግና"	,"ጌና"]	,
"huge":	"ግዙፍ"			,
"human":	"ወዲ ሰብ"			,
"humanitarian":	"ሰብኣዊ"			,
"humanity":	"ፍጥረት ሰብ"			,
"humidity":	"ጠሊ"			,
"humiliate":	"ኣናሸወ"			,
"hump":	"መንዳዓት"			,
"hundred":	"ሚእቲ"			,
"hundred kilos":	"ኩንታል"			,
"hunger":	"ጥሜት"			,
"hungry":	"ጥሙይ"			,
"hunt":	"ሃደነ"			,
"hunter":	"ሃዳናይ"			,
"hurry":	"ታህዋኽ"			,
"hurry":	"ተሃወኸ"			,
"hurry up":	"ቀልጠፈ"			,
"hurt":	"ጉድኣት"			,
"hurt":	"ጐድአ"			,
"hurt oneself":	"ተጎድአ"			,
"husband":	"በዓል ቤት"			,
"hut":	"ኣጉዶ"			,
"hyena":	"ዝብኢ"			,
"hygiene":	"ስነ ጥዕና"	,
"I":	"ኣነ"			,
"idea":	"ሓሳብ"			,
"ideal":	"ዝሰማማዕ"			,
"identify":	"ፈለጠ"			,
"ignorance":	"ድንቁርና"			,
"ignorant":	"ደንቆሮ"			,
"ignore":	"ሻላ በለ"			,
"ill":	"ሕሙም"			,
"illuminate":	"ኣብረሀ"			,
"image":	"ስእሊ"			,
"imagine":	"ሓሰበ"			,
"imitate":	"ቀድሐ"			,
"immediately":	"ብኡንቡኡ"			,
"immobile":	"ዘይንቀሳቐስ"			,
"impatient ":	"ተሃንጠየ"			,
"importance":	"ኣድላይነት"			,
"important":	"ኣገዳሲ"			,
"impossibility":	"ዘይካኣልነት"			,
"impossible":	"ዘይካኣል"			,
"impress":	"ኣደነቐ"			,
"improve":	"ኣመሓየሸ"			,
"in advance":	"ኣቐዲምካ ዝግበር"			,
"in":	"ጠሓለ"		,
"incapable":	"ዘይክእል"			,
"include":	"ወሰኸ"			,
"inconvenience":	"ጸገመ"			,
"increase":	"ወሰኸ"			,
"indeed":	"ብሓቂ"			,
"independence":	"ነጻነት"			,
"independent":	"ነጻ"			,
"indicate":	"ኣመልከተ"			,
"indigestion":	"ዘይሕቀት መግቢ"			,
"industrial":	"ኡንዱስትሪያዋ"			,
"industrial area":	"ዞባ ቤት ዕዮታት"			,
"industrialist":	"ኡንዱስትሪ"			,
"inevitable":	"ዘይተርፍ"			,
"inevitably":	"ግድነት"			,
"infant":	"ሕጻን"			,
"infantile":	"ናይ ሕጻን"			,
"inferior":	"ታሕታይ"			,
"infinite":	"ወሰን ዘአይብሉ"			,
"inflame":	"ኣሕረቐ"			,
"influence":	"ጽልዋ"			,
"inform":	"ኣፍለጠ"			,
"information":	["ሓበሬታ"	,"ወረ"]		,
"ingratitude":	"ዘይምምስጋን"			,
"inhabitant":	"ተቐማጢ"			,
"inheritance":	"ውርሻ"			,
"injure":	"ጎድአ"			,
"injure oneself":	"ተጎድአ"			,
"injury":	"ጉድኣት"			,
"ink":	"ቀለም"			,
"ink well":	"ጥርሙዝ ቀለም"			,
"innocence":	"ንጽህና"			,
"innocent":	"ንጽህ"			,
"inquiry":	"ወረ"			,
"insect":	"ሓሰኻ"			,
"inside":	"ውሽጢ"			,
"insist":	"ብግዲ በለ"			,
"insoluble":	"ዘይፍታሕ"			,
"inspect":	"በጽሐ"			,
"inspector":	"ተቖጻጻሪ"			,
"institute":	"ትካል"			,
"instructive":	"ሃናጺ"			,
"instrument":	"መሳርሒ ኣቕሓ"			,
"insult":	"ጸርፊ"			,
"insult":	"ጸረፈ"			,
"intellectual":	"ምሁር"			,
"intelligence":	"ኣስተውዕሎ"			,
"intelligent":	"ኣስተውዓሊ"			,
"intend":	"ኣመስለ"			,
"intention":	"ዕላማ"			,
"interest":	"ወለድ"			,
"interesting":	"ኣገዳሲ"			,
"interrupt":	"ኣቋረጸ"			,
"intervene":	"ጣልቃ ኣተወ"			,
"intestine":	"መዓንጣ"			,
"introduce":	"ኣላለየ"			,
"introduction":	"መእተዊ"			,
"invade":	"ወረረ"			,
"invalid":	"ዋጋ ዘይብሉ"			,
"invent":	"መሃዘ"			,
"invention":	"ምህዞ"			,
"investigate":	"ኣጽንዐ"			,
"investigation":	"መርመረ"			,
"invisible":	"ዘይረአ"			,
"invitation":	"ዕድመ"			,
"invite":	"ዓደመ"			,
"involve":	"ተኻፈለ"			,
"iron":	"ሓጺን"			,
"ironing":	"እስትራረ"			,
"irrigate":	"መስኖወ"			,
"irritate":	"ኣሕረቐ"			,
"island":	"ደሴት"			,
"isolate":	"ፈለየ"			,
"Italian":	"ኡጣልያዊ"			,
"Italian parsley":	"ፐርሰሜሎ"			,
"item":	"ኣቕሓ"			,
"item of clothing":	"ክዳን"			,
"ivory":	"ስኒ ሓርማዝ"			,
"ivy":	"ኣይቢ ዓይነት ሓረግ"			,
"jacket":	"ጁባ"			,
"jacket":	"ጃኬት"			,
"jalapeño pepper":	"ጒዕ"			,
"jam":	"ማልመላታ"			,
"January":	"ጥሪ"			,
"jaw":	"መንጋጋ"			,
"jealous":	"ቀናአ"			,
"jealousy":	"ቅንኢ"			,
"Jesus Christ":	"የሱስ ክርስቶስ"			,
"jewel":	"ስልማት"			,
"job":	"ስራሕ"			,
"join":	"ሰዓበ"			,
"joke":	"ላግጺ"			,
"jostle":	"ደፋፍአ"			,
"journal":	"ጋዜጣ"			,
"journalist":	"ጋዜጠኛ"			,
"journey":	["ጉዕዞ"	,"መገሻ"]		,
"joy":	"ደስታ"			,
"joyful":	"ድሱት"			,
"judge":	["ፈራዲ"	,"ዳኛ"	,"ፈራዳይ"]	,
"judge":	"ዓራቒት ፈራዲት"			,
"judge":	"ዓራቓይ"			,
"judge":	["ዳነየ"	,"ምፍራድ"	,"ምፍታሕ"]	,
"judgement":	["ኣንፈት"	,"ፍርዲ"]		,
"juicy":	"ፈሳሲ ዘለዎ"			,
"July":	"ሓምለ"			,
"jump":	"ዝላ"			,
"jump":	"ዘለለ"			,
"junction":	"መራኸቢ"			,
"June":	"ሰነ"			,
"junior high school":	"ማእከላይ ደረጃ"			,
"juror":	"ፈራዲ"			,
"jury":	"ፈራዶ"			,
"just":	"ልክዕ"			,
"justify":	"መግለጺ ሃበ"			,
"keep":	"ዓቀበ"			,
"kennel":	"ኣጉዶ"			,
"key":	"መፍትሕ"			,
"kick":	"ነድሐ"			,
"kidney":	"ኩላሊት"			,
"kill":	"ቀተለ"			,
"kilogram":	"ኪሎግራም"			,
"kilometre":	"ኪሎሜተር"			,
"kind":	"ትዑይ"			,
"kind":	"ዓይነት"			,
"kindergarten":	"መውዓል ህጻናት"			,
"kindly":	"ሕያዋይ"			,
"kindness":	"ለውሃት"			,
"king":	"ንጉስ"			,
"kingdom":	"ግዝኣት"			,
"kingly":	"ንጉሳዊ"			,
"kiss":	"ስዕመት"			,
"kiss":	"ሰዓመ"			,
"kitchen":	"ክሽነ"			,
"kitten":	"ውላድ ድሙ"			,
"knead":	"ለወሰ"			,
"knee":	"ብርኪ"			,
"kneel":	"ተምበርከኸ"			,
"knew":	"ፍሉጥ"			,
"knife":	"ካራ"			,
"knight":	"ፈረሰኛ"			,
"knit":	"ኣለመ"			,
"knock":	"ሃረመ"			,
"knot":	"ቁጻር"			,
"know":	"ፈለጠ"			,
"know how to":	"ፍልጠት"			,
"knowledge":	"ፍልጠት"			,
"ladder":	"ኣስካላ"			,
"lady":	"ሰበይቲ"			,
"lair":	"በዓቲ"			,
"lake":	"ቀላይ"			,
"lamb":	"ዕየት"			,
"lamp":	"ፋኑስ"			,
"lampshade":	"ገራድ ብርሃን"			,
"land":	"ዓለበ"			,
"language":	"ቛንቛ"			,
"large":	["ዓብይ"	,"ገዚፍ"]		,
"large intestine":	"ማዓንጣ"			,
"last":	"መጠረሽታ"			,
"late":	["ድንጉይ"	,"ዝሓለፈ"]		,
"latecomer":	"ደንጓዩ"			,
"lateness":	"ድንጉይ"			,
"latest":	"መጠረሽታ"			,
"laugh":	"ሰሓቐ"			,
"laugh":	"ተላገጸ"			,
"laughter":	"ሳሓቕ"			,
"law":	"ሕጊ"			,
"lawyer":	"ጠበቓ"			,
"lay":	"ኣቐመጠ"			,
"lay eggs":	"እንቋቑሖ ወለደት"			,
"laziness":	"ትህኪት"			,
"lazy":	"ሃካይ"			,
"lead":	["ኣምረሐ"	,"መርሐ"]		,
"leader":	"መራሒ"			,
"leaf":	"ቆጽሊ"			,
"leak":	"ሞሎቐ"			,
"lean":	"ቀጢን"			,
"lean on":	"ተደገፈ"			,
"lean out":	"ደነነ"			,
"leap":	"ነጠረ"			,
"learn":	"ተማህረ"			,
"learned":	"ሊቕ"			,
"least":	"ጎደሎ"			,
"leather":	"ቆርበት"			,
"leave":	"ገደፈ"			,
"lecture":	"ስብከት"			,
"left":	"ጸጋም"			,
"left":	"ተረፈ"			,
"leg":	"ዳንጋ"			,
"leg muscles":	"ሙሕኹልቲ"			,
"legacy":	"ውርሻ"			,
"legend":	"ኣፈ ታሪኽ"			,
"legs":	"ሙሕኹልቲ"			,
"lemon":	"ለሚን"			,
"lemon tree":	"ገረብ ለሚን"			,
"lend":	"ኣለቀሐ"			,
"lengthen":	"ኣንወሐ"			,
"lens":	"መርዓት ዓይኒ"			,
"lentils":	"ብርስን"			,
"leopard":	"ነብሪ"			,
"less":	"ጎደሎ"			,
"lesson":	"መጽናዕቲ ትምህርቲ"			,
"let":	"ሓደገ"			,
"letter":	"ደብዳቤ"			,
"letter":	"ፊደል"			,
"letter box":	"ቦስጣ ሳጹን"			,
"lettuce":	"ሳላጣ"			,
"level":	"ማዕረ"			,
"liar":	"ሓሳዊ"			,
"liberal":	"ሰፊሕ ሓሳብ"			,
"liberty":	"ሓርነት"			,
"library":	"ቤተ ንባብ"			,
"lick":	"ለሓሰ"			,
"lid":	"መኽደኒ ድስቲ"			,
"lie":	"ሓሶት"			,
"lie":	"ተጋደመ"			,
"life":	"ሂወት"			,
"lift":	"ኣልዓለ"			,
"ligament":	"ጂማት"			,
"light":	"ፈኲስ"			,
"light":	"ብራሃን"			,
"light":	"ኣብረሀ"			,
"light up":	"ወለዐ"			,
"likable":	"ፍሕሽው"			,
"like":	"ከም"			,
"limb":	"መሓውር"			,
"lime":	"ለሚን"			,
"limit":	"ደረት"			,
"limit":	"ወሰነ"			,
"line":	"መስመር"			,
"linen":	"ዓለባ"			,
"lining":	"ፎደራ"			,
"link":	"ሰንሰለት"			,
"lion":	"ኣንበሳ"			,
"lip":	"ከንፈር"			,
"liquid":	"ፈሳሲ"			,
"list":	"ዝርዝር"			,
"listen":	"ሰምዐ"			,
"listen to":	"ኣድመጸ"			,
"liter":	"ሊተር"			,
"literature":	"ስነ ጽሑፋ"			,
"little":	"ንእሽተይ"			,
"live":	"ሃለወ"			,
"liven":	"ህይወት ሃበ"			,
"liver":	["ከብዲ"	,"ጸላም አብዲ"]		,
"living":	"ሂወታዊ"			,
"living room":	"መዕረፊ ክፍሊ"			,
"load":	"ጽዕነት"			,
"load":	"ጸዓነ"			,
"loading":	"ጽዕነት"			,
"loan":	"ልቓሕ"			,
"loan":	"ኣለቀሐ"			,
"loathe":	"ጸልአ"			,
"local":	"ዞባዊ"			,
"locality":	"ቦታ"			,
"lock":	"መሽገጥ"			,
"lock up":	"ዓጸወ"			,
"locomotive":	"ተንቀሳቓሲ"			,
"locust":	"ኣንበጣ"			,
"loneliness":	["ጽምዋ"	,"ብሕትውና"]		,
"lonely":	"ጽምው"			,
"long":	"ነዊሕ"			,
"long":	"ነዊሕ ግዝ"			,
"long lived":	"ነዊሕ ጸናሒ"			,
"long sigh":	"ኣስተንፈሰ"			,
"look":	"ተመልከተ"			,
"look after":	"ተኸናኸነ"			,
"look at":	"ጠመተ"			,
"loosen":	"ነቐለ"			,
"lord":	"ጎይታ"			,
"lorry":	"መኪና ጽዕነት"			,
"lose":	"ተሳዓረ"			,
"loser":	"ስዑር"			,
"loss":	"ክስራን"			,
"loud":	"ጫውጫውታ ዘለዎ"			,
"love":	"ፍቕሪ"			,
"love":	"ኣፍቀረ"			,
"love with":	"ፍቑር"			,
"loving":	"ፍቑር"			,
"low":	"ታሕቲ"			,
"lower":	["ነከየ"	,"ኣትሓተ"]		,
"luck":	"ዕድል"			,
"lunch":	"ቆረሰ"			,
"lung":	"ሳንቡእ"			,
"lungs":	"ሳንቡእ"			,
"luxury":	"ጣዐሚ"	,
          "machine gun":	"ማሺን ጋን"			,
"Madame":	"ወይዘሮ"			,
"magical":	"ሽሕራዊ"			,
"magnificent":	"ዘደንቕ"			,
"mail":	"ደብዳቤ"			,
"mailman":	"ቦስጠኛ"			,
"main":	"ቀንዲ"			,
"maintain":	"ናበየ"			,
"maize":	"ዑፉን"			,
"make":	"ገበረ"			,
"make a hole":	"ኣንኮለ"			,
"make bigger":	"ኣዕበየ"			,
"make up":	"ኣቖመ"			,
"make widely known":	"ቀልዐ"			,
"male":	"ተባዕታይ"			,
"malicious":	"ሃሳይ"			,
"mammal":	"መጥበዊ"			,
"man":	"ሰብኣይ"			,
"manage":	"ኣመሓደረ"			,
"manager":	"ሓለቓ"			,
"mandate":	"ትእዛዝ"			,
"manifest":	"ኣግሃደ"			,
"mankind":	"ፍጥረት ሰብ"			,
"manner":	"ኣገባብ"			,
"manufacture":	"ሰርሐ"			,
"many":	"ብዙሕ"			,
"map":	"ካርታ"			,
"marble":	["ባሊና"	,"እምነ በረድ"]		,
"march":	"መጋቢት"			,
"marine":	"ባሕራዊ"			,
"maritime":	"ናይ ባሕሪ"			,
"mark":	"ምልክት"			,
"marriage":	"መርዓ"			,
"married ":	"ተመርዓወ"			,
"marry off":	"ኣመርዓወ"			,
"marvellous":	"ዘደንቕ"			,
"mass":	"ቅዳሴ"			,
"mass":	"እኩብ"			,
"massage":	"ምድራዝ"			,
"master":	"መም ህር"			,
"match":	"ክርቢት"			,
"mate":	"ብጸይቲ"			,
"mate":	"ብጻይ"			,
"material":	"ኣቑሑ ህንጻ"			,
"matter":	"ጉዳይ"			,
"matter":	"ኣገደሰ"			,
"maturity":	"ብስለት"			,
"May":	"ጉንበት"			,
"mayor":	"ከንቲባ"			,
"me":	"ኣነ"			,
"mead":	"ሜስ"			,
"meal":	"ብልዒ"			,
"mean":	"ሕሱም"			,
"measles":	"ንፍዮ"			,
"measure":	"ዓቀነ"			,
"measurement":	"ዓቐን"			,
"meat":	"ስጋ"			,
"mechanic":	"መካኒክ"			,
"medal":	"መዳልያ"			,
"medication":	"መድሃኒት"			,
"medicine":	"ሕክምና"			,
"medium":	"ማእከል"			,
"meet":	"ተራኸበ"			,
"meeting":	"ኣኼባ"			,
"melt":	"ሓቐቐ"			,
"melting":	"ምሕቃቐ"			,
"member":	"ኣባል"			,
"Member of Parliament":	"ወኪል ህዝቢ"			,
"memory":	"ዝኽረት"			,
"mend":	"ኣዐረየ"			,
"mention":	"ረቝሐ"			,
"merchant":	"ነጋዳይ"			,
"mercy":	"ምሕረት"			,
"merit":	"ብቕዓት"			,
"messenger":	"መልእኽተኛ"			,
"metal":	"ብረት"			,
"metallic":	"ብረታዊ"			,
"meteorology":	"ስነ ኣየር"			,
"meter":	"ቆጻሪ"			,
"method":	"ቀጥዒ"			,
"metre":	"ሜተር"			,
"middle":	"ማእከላይ"			,
"middle":	"ማእከል"			,
"middle school":	"ማእከላይ ደረጃ"			,
"midnight":	"ፍርቂ ለይቲ"			,
"migrant":	"ስደተኛ"			,
"military":	"ወተሃበራዊ"			,
"milk":	"ጸባ"			,
"milk man":	"በዓል ጸባ"			,
"milk woman":	"በዓልቲ ጸባ"			,
"millimetre":	"ሚሊ ሜተር"			,
"mind":	"ጓሰየ"			,
"mine":	"ናተይ"			,
"mineral":	"ማዕድን"			,
"minister":	"ሚኒስተር"			,
"minor":	["ንእሽቶ"	,"ንእሽተይ"]		,
"minor":	"ፈሓር ማዕድን"			,
"minority":	"ውሑዳን"			,
"minute":	"ደቒቕ"			,
"miracle":	"ትኣምር"			,
"mirror":	"መስትያት"			,
"misdemeanour":	"በደል"			,
"misfortune":	"ሕማቕ ዕድል"			,
"miss":	"ወይዘሪት"			,
"miss":	"ሰሓተ"			,
"missing":	"ጎደለ"			,
"missionary":	"ሰባኺ"			,
"mistake":	"ጌጋ"			,
"Mister":	"ኣቶ"			,
"mix":	"ሓዋወሰ"			,
"mixed":	"ሕውስዋስ"			,
"moan":	"ጥርዓን"			,
"mob":	"ጽቕጥቅጥ"			,
"mobile":	"ተንቀሳቓሲ"			,
"mocking":	"ሓጫጪ"			,
"mode":	"ቅዲ ሞዳ"			,
"mode of transport":	"መጓዓዝያ"			,
"model":	"ቅዲ"			,
"modern":	"ግዚያዊ"			,
"modest":	"ምቕሉል"			,
"modesty":	"ትሕትና"			,
"moisture":	"ጠሊ"			,
"momentary":	"ግዚያዊ"			,
"monastery":	"ገዳም"			,
"Monday":	"ሰኑይ"			,
"money":	"ሰልዲ"			,
"monk":	"ፈላሲ"			,
"monkey":	"ህበይ"			,
"month":	"ወርሒ"			,
"monthly":	"ወርሓዊ"			,
"monument":	"ሓወልቲ"			,
"moral":	"ሞራል"			,
"more":	"ዝያዳ"			,
"more than enough":	"ብብዚሒ"			,
"morning":	"ናይ ንጉሆ"			,
"morning":	"ንጉሆ"			,
"mortgage":	"ልቓሕ"			,
"mosque":	"መስጊድ"			,
"mosquito":	"ጣንጡ"			,
"mother":	"ኣደ"			,
"motionless":	"ዘይንቀሳቐስ"			,
"motive":	"ምኽንያት"			,
"motor":	"ሞተር"			,
"motorbike":	"ሞቶ"			,
"mountain":	"ጎቦ"			,
"mountainous":	"ጎባዊ"			,
"mouse":	"ኣንጭዋ"			,
"mouth":	"ኣፍ"			,
"move":	"ቦታ ቀየረ"			,
"move away":	"ረሓቐ"			,
"move everything out":	"ገዓዘ"			,
"moved":	"ደንገጸ"			,
"much":	"ብዙሕ"			,
"mucus":	"ንፋጥ"			,
"mud":	"ጭቃ"			,
"muddy":	"ጭቃዊ"			,
"mule":	"በቕሊ"			,
"multiple":	"ርባሕ"			,
"multiplication":	"ምርባሕ"			,
"mumps":	"ጽጌዕ"			,
"municipal":	"ምምሕዳር ከተማ"			,
"murder":	"ቀተለ"			,
"murderer":	"ቀታሊ"			,
"murderous":	"ቀታሊ"			,
"murmur":	"ኣዕዘምዘመ"			,
"muscle":	"ጭዋዳ"			,
"museum":	"ቤተ መዘከር"			,
"mushroom":	"ቃንጥሻ"			,
"music":	"ሙዚቃ"			,
"musician":	"ሙዚቀኛ"			,
"mustard":	"ሰናፍጭ"			,
"mutton":	"ስጋ በጊዕ"			,
"mysterious":	"ምስጢራዊ"			,
"mystery":	"ምስጢር"			,
"nail":	"መስማር"			,
"nail file":	"መብረድ"			,
"naive":	"ገርሂ"			,
"narrow":	"ጽቢብ"			,
"nastiness":	"ርግመት"			,
"nasty":	"ግናይ"			,
"national":	"ሃገራዊ"			,
"nationality":	"ዜግነት"			,
"natural":	"ባህርያዊ"			,
"navigate":	"ሰፈፈ"			,
"near":	"ቀረበ"			,
"nearly":	"ጥቓ"			,
"neat":	"ጽሩይ"			,
"neatness":	"ጽሬት"			,
"necessary":	"ኣድላይ"			,
"necessity":	"ኣድላይነት"			,
"neck":	"ክሳድ"			,
"necktie":	"ክራባታ"			,
"need":	"ደለየ"			,
"needle":	"መርፍእ"			,
"neglect":	"ሸለል በለ"			,
"negligence":	"ሸለልትነት"			,
"negligent":	"ዘይግደስ"			,
"neighbourhood":	"ጉርብትና"			,
"neighbouring":	"ጎረቤት"			,
"nephew":	"ወዲ ሓዊ"			,
"nephew":	"ወዲ ሓብቲ"			,
"nest":	"ገዛ ዑፍ"			,
"nest":	"ገዛ ዑፍ ሰርሐ"			,
"never":	"ብፍጹም"			,
"new":	"ሓዲሽ"			,
"new year":	"ሓዲሽ ዓመት"			,
"news":	"ወረ"			,
"newspaper":	"ጋዜጣ"			,
"next":	"ዝስዕብ"			,
"next":	"ቀጺሉ"			,
"nice":	["ሕያዋይ"	,"ጥዑም"]		,
"niece ":	"ጓል ሓዊ"			,
"niece":	"ጓል ሓብቲ"			,
"night":	"ለይቲ"			,
"night time":	"ለይታዊ"			,
"nightstand":	"ኮመዲኖ"			,
"nine":	"ትሽዓተ"			,
"nineteen":	"ዓሰርተ ትሽዓተ"			,
"ninety":	"ተስዓ"			,
"ninth grade":	"ታሽዓይ ክፍሊ"			,
"no":	"እምቢ"			,
"nobility":	"ጎይትነት"			,
"noise":	"ጫውጫውታ"			,
"noisy":	"ጫውጫውታ ዘለዎ"			,
"normal":	"ልሙድ"			,
"north":	"ሰሜን"			,
"northern":	"ሰሜናዊ"			,
"nose":	"ኣፍንጫ"			,
"nostril":	"መስኮት ኣፍንጫ"			,
"note":	"ነጥቢ ሓዘ"			,
"notebook":	"ጥራዝ"			,
"nothing":	"ገለኳ"			,
"notice":	"ምልክታ"			,
"notify":	"ኣፍለጠ"			,
"novel":	"ልብ ወለድ"			,
"novelist":	"ተራኺት"			,
"novelist":	"ተራኺ"			,
"November":	"ሕዳር"			,
"now":	"ሕጂ"			,
"numb":	"ኣደቀሰ"			,
"number":	"ቁጽሪ"			,
"numerous":	"ብዙሓት"			,
          "oak":	"ኦክ"			,
"oath":	"ማሕላ"			,
"obedience":	"ተኣዛዝነት"			,
"obedient":	"እዙዝ"			,
"obey":	"ተኣዘዘ"			,
"objection":	"ጥርዓን"			,
"oblige":	"ኣገደደ"			,
"observation":	"ትዕዝብቲ"			,
"observe":	"ተዓዘበ"			,
"obstacle":	"ዕንቅፋት"			,
"occasion":	"ኣጋጣሚ"			,
"occupy":	"ሓዘ"			,
"ocean":	"ውቅያኖስ"			,
"October":	"ጥቅምቲ"			,
"odd":	"ዘይጽምዲ ቁጽሪ"			,
"odour":	"ጨና"			,
"off":	"ነፈረ"			,
"offence":	"ኣሕረቐ"			,
"offend":	"ኣቐየመ"			,
"offend against":	"ኣሕረቐ"			,
"offer":	"ወፈየ"			,
"officer":	"መኮነን"			,
"official":	"ወግዓዊ"			,
"often":	"መብዛሕእቱ ግዝ"			,
"oil":	"ዘይቲ"			,
"old":	"ኣረጊት"			,
"old age":	"እርጋን"			,
"olive tree":	"ኣውሊዕ"			,
"on top":	"ኣብ ልዕሊ"			,
"once again":	"እንደገና"			,
"one":	"ሓደ"			,
"one time":	"ሓደ ግዜ"			,
"onion":	"ሽጉርቲ ቀይሕ"			,
"only":	"በይኑ"			,
"open":	"ከፋት"			,
"open":	"ከፈተ"			,
"opening":	["ክፋት"	,"ኣፍ"]		,
"openly":	"ብቕንዕና"			,
"opera":	"ኦፐራ"			,
"operate":	"ጠብሐ"			,
"operating room":	"ክፍሊ"			,
"operation":	"መጥባሕቲ"			,
"opinion":	"ርእይቶ"			,
"opportunity":	"ኣጋጣሚ"			,
"oppose":	"ተጻረረ"			,
"opposite":	"ኣንጻር"			,
"orange":	"ኣራንቺ"			,
"orange juice":	"ጹማቕ አራንቺ"			,
"orange tree":	"ገረብ ብርትኳን"			,
"order":	"ትእዛዝ"			,
"order":	"ኣዘዘ"			,
"ordinarily":	"ልሙዳዊ"			,
"ordinary":	"ልሙድ"			,
"organ":	"ኦርጋን"			,
"organize":	"ኣዳለወ"			,
"oriental":	"ምብራቃስ"			,
"origin":	"መበቆል"			,
"original":	"መበቆላዊ"			,
"orphan":	"ዘኸታም"			,
"ostrich":	"ሰገን"			,
"otherwise":	"እንተዘይኮነ"			,
"ought":	"ይግባእ"			,
"ours":	"ናትና"			,
"out of tune":	"ቃና ዘይብሉ"			,
"outside":	"ወጻኢ"			,
"oval":	"ቅርጺ እንቋቒሖ"			,
"oven":	"እቶን"			,
"overcome":	"ሰዓረ"			,
"owe":	"ተኣወደ"			,
"owl":	"ጉንጓ"			,
"own":	"ኣጥረየ"			,
"owner":	"ወናኒ"			,
"ownership":	"ዋንነት"			,
"ox":	"ብዕራይ"			,
"package":	"ጥቕላል ባኮ"			,
"packing":	"መጠርነፊ"			,
"page":	"ገጽ"			,
"pail":	"ሳንኮሎ"			,
"pain":	"ቃንዛ"			,
"pain":	"ተሳቐየ"			,
"painful":	"መቐንዘዊ"			,
"paint":	"ሰኣለ"			,
"painter":	["ሰኣሊ"	,"ለማጻይ"]		,
"painting":	"ስእሊ"			,
"pair":	"ጽምዲ"			,
"pal":	"መሓዛ"			,
"palace":	"ኣዳራሽ"			,
"pale":	"ጽምልው"			,
"pale":	"ጻዕደወ"			,
"palm":	"ከብዲ ኢድ"			,
"palm tree":	"ስየ"			,
"pan":	"ድስቲ"			,
"papaya":	"ፓፓዮ"			,
"paper":	"ወረቐት"			,
"parachute":	"ጃንጥላ"			,
"paragraph":	"ዓንቀጽ"			,
"parallel":	"ማዕረ ማዕረ"			,
"pardon":	"ምሕረት"			,
"parent":	"ወለዲ"			,
"parish":	"ቤተ ጸሎት"			,
"park":	"መናፈሻ ቦታ"			,
"park":	"ጠጠ ኣበለ"			,
"parking ticket":	"መቕጻዕቲ"			,
"participate":	"ተሳተፈ"			,
"particular":	"ፍሉይ"			,
"particularly":	"ብፍላይ"			,
"partridge":	"ቆቕሕ"			,
"pass":	["ምሕላፍ"	,"ሓለፈ"]		,
"pass on":	"ኣመሓላለፈ"			,
"passage":	"መተሓላለፊ"			,
"passed":	"ሓሊፈ"			,
"passenger":	["መንገደኛ"	,"ገያሻይ"]		,
"passion":	"ተምሳጥ"			,
"past":	"ሕሉፍ"			,
"paste":	"ባስታ"			,
"pastor":	"ቀሺ"			,
"pastry":	"እንዳ ዶልሺ"			,
"patch":	"ለገበ"			,
"path":	"መሕለፊ"			,
"patience":	"ትዕግስቲ"			,
"patient":	"ዓቃል"			,
"patient":	"ተሓካሚ"			,
"pattern":	"ቅዲ"			,
"pause":	"ጠጠው በለ"			,
"pay":	"መሃያ"			,
"pay":	"ከፈለ"			,
"pea":	"ዓይኒ ዓተር"			,
"peace":	"ሰላም"			,
"peaceful":	"ሰላማዊ"			,
"peach":	"ኩኽ"			,
"peanuts":	"ፉል"			,
"pearl":	"ሉል"			,
"peas":	"ዓይኒ ዓተር"			,
"peck":	"ወግአ"			,
"pedestrian":	"ኣጋር"			,
"peel":	"ቅላጥ"			,
"peel":	"ቀለጠ"			,
"pen":	"ፐሮ"			,
"penal":	"ገበናዊ"			,
"penalty":	"መቕጻዕቲ"			,
"pencil":	"ርሳስ"			,
"pencil box":	"እንዳ ርሳስ"			,
"pendulum clock":	"ሰዓት መንደቕ"			,
"penknife":	"ሰንጢ"			,
"people":	"ህዝቢ"			,
"pepper":	"ፐፐሮኒ"			,
"perfect":	"ልክዕ"			,
"perfection":	"ልክዕነት"			,
"perfectly":	"ብጽፈት"			,
"perform":	"ተጻወተ ምዚቃ"			,
"performance":	"ሙዚቃዊ ጸወታ"			,
"period":	"እዋን"			,
"permission":	"ፍቓድ"			,
"permit":	"ኣፍቀደ"			,
"persist":	"ጸንዐ"			,
"person":	"ሰብ"			,
"personal":	"ብሕታዊ"			,
"personnel":	"ሰራሕተኛታት"			,
"persuade":	"ኣእመነ"			,
"petrol":	"በንዚን"			,
"pharmacist":	"ፋርማሲያዊ"			,
"pharmacy":	"ፋርማሲ"			,
"photograph":	"ስእሊ"			,
"photograph":	"ሰኣለ"			,
"photographer":	"ሰኣሊ"			,
"piano":	"ፒያኖ"			,
"pick":	"ኣረየ"			,
"pick axe":	"ኣፍራዛ"			,
"pick up":	"ጠርነፈ"			,
"picture":	"ስእሊ"			,
"piece":	"ቁራጽ"			,
"pig":	"ሓሰማ"			,
"pig farm":	"መራብሒ ሓሰማ"			,
"pigeon":	"ርግቢት"			,
"piggy bank":	"ካሳ"			,
"pill":	"ከኒና"			,
"pillow":	"መተርኣስ"			,
"pilot":	"መራሕ ነፋሪት"			,
"pin":	"መርፍእ ወረቐት"			,
"pipe":	"ቱቦ"			,
"pit":	"ጉድጓድ"			,
"pity":	"ድንጋጸ"			,
"place":	"ቦታ"			,
"place":	"ኣንበረ"			,
"plain":	"ጎልጉል"			,
"plan":	"መደብ"			,
"plant":	"ተኽሊ"			,
"plant":	"ተኸለ"			,
"plate":	"ሸሓኒ"			,
"platform":	"መድረክ"			,
"play":	"ጸወታ"			,
"play":	"ጻውቲ"			,
"player":	"ተጻዋቲት"			,
"player":	"ተጻዋቲ"			,
"plead":	"ተማሕጸነ"			,
"please":	"ብኽብረትኩም"			,
"pleasure":	"ደስታ"			,
"plug":	"መኽደኒ"			,
"plumber":	"ሰራሕ ቱቦ ማይ"			,
"pocket":	"ጁባ"			,
"poem":	"ግጥሚ"			,
"point":	["ጫፍ"	,"ነጥቢ"]		,
"point out":	"ኣርኣየ"			,
"poison":	"ስሚ"			,
"poisonous":	"መርዛም"			,
"police":	"ፖሊስ"			,
"polish":	"ወልወለ"			,
"polite":	"ልዙብ"			,
"politeness":	"ትሕትና"			,
"political":	"ፖለቲካዊ"			,
"politician":	"ፖለቲክ"			,
"pomp":	"ፖምፓ"			,
"pool":	"ንእሽቶ ቀላይ"			,
"poor":	["ድኻ"	,"ነዳይ"]		,
"pope":	"ጳጳስ"			,
"popular":	"ፖፕላር"			,
"population":	"ህዝቢ"			,
"port":	"ወደብ"			,
"porter":	"ረፋዕ"			,
"portfolio":	"እንዳ ገንዘብ"			,
"portrait":	"ስእሊ"			,
"position":	"ኣቀማምጣ"			,
"possess":	"ወነነ"			,
"possession":	"ዋንነት"			,
"possible":	"ዝከኣል"			,
"possible":	"ተኽእሎ"			,
"post card":	"ካርቶሊና"			,
"post office":	"ቦስጣ ቤት"			,
"postal":	"ብቦስጣ"			,
"poster":	"ፖስተር"			,
"pot":	"ጻሕሊ"			,
"potato":	"ድንሽ"			,
"pound":	"ፍርቂ ኪሎ"			,
"pour":	"ከዓወ"			,
"pour out":	"ቐድሐ"			,
"poverty":	"ድኽነት"			,
"powder":	"ባሩድ"			,
"power":	"ሓይሊ"			,
"powerful":	"ሓያል"			,
"practical":	"ግብራዊ"			,
"practice":	"ልምምድ"			,
"practise":	"ተላመደ"			,
"praise":	"ናእዳ"			,
"pray to":	"ጸሌየ"			,
"prayer":	"ጸሉት"			,
"preach":	"ሰበኸ"			,
"precaution":	"ጥንቃቐ"			,
"precise":	"ልክዕ"			,
"precisely":	"ብግቡእ"			,
"prefer":	"መረጸ"			,
"preference":	"ምርጫ"			,
"preparation":	"ቅርርብ"			,
"prepare":	"ቀረበ"			,
"prescribe":	"ኣዘዘ"			,
"presence":	"ህላዌ"			,
"present":	"ህሉው"			,
"president":	"ኣቦ መንበር"			,
"press":	"ማዕከን ወረ"			,
"press":	"ጸቐጠ"			,
"press release":	"ጋዜጣዊ መግለጺ"			,
"pretty":	"ጽቡቕ"			,
"prevent":	"ዓገተ"			,
"previous":	["ዝሓለፈ"	,"ድሮ"]		,
"prey":	"ተሃዳኒ"			,
"price":	"ዋጋ"			,
"prick":	"ወግአ"			,
"prickle":	"እሾኽ"			,
"prickly":	"ኣሻኹ"			,
"pride":	"ሓበን"			,
"priest":	"ቀሺ"			,
"primary":	"መባእታዊ"			,
"prince":	"ወዲ ንጉስ"			,
"princess":	"ጓል ንጉስ"			,
"principal":	"ቀንዲ"			,
"principal":	["ዳይረክቶር"	,"አማሓዳሪ"]		,
"principle":	"መትከል"			,
"print":	"ቅርጺ"			,
"print":	"ሓተመ"			,
"prison":	"ቤተ ማሕቡስ"			,
"prisoner":	"ሕቡስ"			,
"privilege":	"መሰል"			,
"probable":	"ምናልባት"			,
"problem":	"ግድል"			,
"proceed":	"ንቕድሚት ኣምረሐ"			,
"proclaim":	"ኣወጀ"			,
"produce":	"ርባሕ"			,
"produce":	"ኣፍረየ"			,
"profession":	"ሞያ"			,
"professional":	"ሞያዊ"			,
"professor":	"ፕሮፈሰር"			,
"profit":	"መኽሰብ"			,
"profitable":	"ረብሓ ዘለዎ"			,
"program":	"መደብ"			,
"progress":	"ምዕባለ"			,
"prohibit":	"ኣገደ"			,
"promise":	"መብጽዓ"			,
"promise":	"ተመባጸዐ"			,
"pronounce":	"ኣድመጸ"			,
"proof":	"መረጋገጺ"			,
"property":	"ዋንነት"			,
"prophet":	"ነቢይ"			,
"prosecution":	"ክሲ"			,
"protect":	"ተኸላኸ"			,
"protest":	"ተቓወመ"			,
"protestant":	"ከኒሻ"			,
"proud":	"ኩሩዕ"			,
"proudly":	"ብኹርዓት"			,
"prove":	"ኣእመነ"			,
"provide":	"ኣምጸአ"			,
"provinces":	"ኣውራጃ"			,
"provoke":	"ኣስዓበ"			,
"public":	"ህዝባዊ"			,
"public":	"ህዝቢ"			,
"pull":	"ሰሓበ"			,
"pumpkin":	"ዱባ"			,
"punish":	["ቀጽዐ"	,"ኣተኻኸለ"]		,
"pupil":	"መርዓት ዓይኒ"			,
"purchaser":	"ዓዳጊ"			,
"pure":	"ጽሩይ"			,
"purr":	"ሩር በለ"			,
"pursuit":	"ክሲ"			,
"push":	"ደፍአ"			,
"push aside":	"ፈላለየ"			,
"put":	"ኣቐመጠ"			,
"put into words":	"ገለጸ"			,
"put out":	"ኣጥፈአ"			,
"put out of shape":	"ኣትሞመ"			,
"put right":	"ኣተኻኸለ"			,
"put up":	"ክብ ኣበለ"			,
"quality":	"ብቕዓት"			,
"quarter":	"ርብዒ"			,
"question":	"ሕቶ"			,
"quick":	"ቅልጡፍ"			,
"quickly":	"ብቑልጡፍ"			,
"quickness":	"ቅልጣፈ"			,
"quiet":	["ህድኣት"	,"ህዱእ"]		,
"quiet down":	"ኣህደአ"			,
"quietly":	"ብህድኣት"			,
"quietness":	"ህዱእ"			,
"quiver":	"ኣንፈጥፈጠ"			,
"rabbit":	"ማንቲለ"			,
"rabbit hutch":	"ገዛ ማንቲለ"			,
"race":	"ቅድድም"			,
"radiator":	"መሞቒ"			,
"radio":	"ራዲዮ"			,
"rag":	"ጨርቂ"			,
"rage":	"ቁጠዓ"			,
"rail":	"መደንደል"			,
"rain":	"ዝናብ"			,
"rain":	"ዘነበ"			,
"rainbow":	"ቀስተ ደመና"			,
"raise":	"ኣልዓለ"			,
"raisins":	"ዘቢብ"			,
"rake":	"ሓግሓገ"			,
"ranch":	"ምርባሕ እንስሳ"			,
"rapid":	"ቅልጡፍ"			,
"rare":	"ሳሓቲ"			,
"rat":	"ኣንጭዋ"			,
"rate":	"ቀረጽ"			,
"reach":	"በጽሐ"			,
"read":	"ነበበ"			,
"read again":	"እንደገና ኣንበበ"			,
"reader":	"ኣንባቢት"			,
"reader":	"ኣንባቢ"			,
"reading":	"ንባብ"			,
"real":	"ሓቂ"			,
"reality":	"ክውንነት"			,
"reap":	"እኽሊ ኣኸበ"			,
"reason":	"ምኽንያት"			,
"receipt":	"ቅብሊት"			,
"receive":	"ተቐበለ"			,
"recent":	"ቀረባ እዋን"			,
"recently":	"ኣብዚ ቀረባ እዋን"			,
"reception":	"መቐበል ጋሻ"			,
"recess":	"ዕረፍቲ"			,
"recognize":	"ኣለለየ"			,
"recover":	"እንደና ረኸበ"			,
"recovery":	"ምሕዋይ"			,
"rectangle":	"ርቡዕ ኩርናዕ"			,
"red":	"ቀይሕ"			,
"red chilli pepper":	"በርበረ"			,
"reduce":	"ነከየ"			,
"referee":	"መንጎኛ"			,
"reflection":	"ነጸብራቕ"			,
"reform":	"ጸገነ"			,
"refuse":	"ኣብየ"			,
"regain":	"እንደና ረኸበ"			,
"region":	"ከባቢ"			,
"regret":	"ጣዕሳ"			,
"regulation":	"ስምምዕ"			,
"rehearsal":	"ድግማ"			,
"reject":	"ነጸገ"			,
"rejoin":	"ኣርከበ"			,
"relative":	"ዘመድ"			,
"relaxation":	"ዕረፍቲ"			,
"release":	"ፈተሐ"			,
"reliable":	"ርግጸኛ"			,
"reliance":	"እምነት"			,
"relief":	"ምፍጓስ"			,
"religion":	"ሃይማኖት"			,
"religious":	"ሃይማኖታዊ"			,
"remain":	"ተረፈ"			,
"remark":	"ብህሊት"			,
"remedy":	"መድሃኒት"			,
"remember":	"ዘከረ"			,
"remind":	"ኣዘከረ"			,
"remorse":	"ጣዕሳ"			,
"remove":	"ኣልገሰ"			,
"renew":	"ኣሐደሰ"			,
"rent":	"ክራይ"			,
"rent":	"ኣካረየ"			,
"repair":	"ኣዐረየ"			,
"repeat":	"ደገመ"			,
"replace":	"ተክአ"			,
"reply":	["መለሰ"	,"ምላሽ ሃበ"]		,
"represent":	"ወከለ"			,
"representative":	"ወኪል"			,
"reptile":	"ለማሚ"			,
"republic":	"ሩፑብሊክ"			,
"request":	"ጠለበ"			,
"require":	"ኣድለየ"			,
"rescue":	"ኣድሓነ"			,
"rescuer":	"መድሓኒ"			,
"reserve":	"ቅሙጥ"			,
"residence":	"ትቕመጠሉ ቦታ"			,
"resist":	"ተቓወመ"			,
"resistance":	"ተቓዉሞ"			,
"resolution":	"ውሳኔ"			,
"resolve":	"ፈተሐ"			,
"resources":	"ሃብቲ"			,
"respect":	"ክብረት"			,
"respect":	"ኣኸበረ"			,
"respectful":	"ኣኽባሪ"			,
"responsibility":	"ሓላፍነት"			,
"rest":	"ዕረፍቲ"			,
"rest":	"ኣዕረፈ"			,
"restart":	"እንደገና ጀመረ"			,
"restaurant":	"ቤተ ብልዒ"			,
"result":	"ውጽኢት"			,
"retirement":	"ጥሮታ"			,
"return":	"እንደገና መጸ"			,
"return ticket":	"ቲከት መምለሲ"			,
"reunion":	"ኣኼባ"			,
"reveal":	"ቀልዕ"			,
"revenge":	"ሕነ"			,
"reverse":	"ግምጥልሽ"			,
"review":	"ደገመ"			,
"revolution":	"ሰዉራ"			,
"reward":	"ጻማ"			,
"rhythm":	"ረምታ"			,
"ribs":	"መሰናግለ"			,
"rice":	"ሩዝ"			,
"rich":	"ሃብታም"			,
"rid of":	"ወገደ"			,
"ride":	"ተወጥሐ"			,
"rifle":	"ጠበንጃ"			,
"right":	"ቅኑዕ"			,
"right to vote":	"መሰል ድምጺ"			,
"rightly":	"ብግቡእ"			,
"ring":	"ደወለ"			,
"rip up":	"ቀደደ"			,
"rise":	"እንደገና ተንሰአ"			,
"risky":	"ሓደጋ"			,
"river":	"ዋሕዚ"			,
"road":	"መንገዲ"			,
"roast":	"ጥቡስ ስጋ"			,
"rob":	"ዘመተ"			,
"robbery":	"ስርቂ"			,
"rock":	"ከውሒ"			,
"rocky":	"ከውሓዊ"			,
"roof":	"ናሕሲ"			,
"room":	"ክፍሊ"			,
"roomy":	"ሰፊሕ"			,
"rooster":	"ደርሆ"			,
"root":	"ሱር"			,
"rope":	"ገመድ"			,
"rose":	"ጽጌረዳ"			,
"rose bush":	"ገረበ ጽግረዳ"			,
"rosemary":	"ሮዝመሪ"			,
"rot":	"መሽመሸ"			,
"rough":	"ሓርፋፍ"			,
"round":	"ከቢብ"			,
"round":	"ክቢ"			,
"round":	"ኣኽበበ"			,
"route":	"መንገዲ"			,
"royal":	"ንጉሳዊ"			,
"rub":	"ፋሕፈሐ"			,
"ruin":	"ዕንወት"			,
"rule":	"ስርዓት"			,
"ruler":	"መስመር"			,
"run":	"ጎየየ"			,
"runner":	"ጎያዩ"			,
"rural":	"ገጠራዊ"			,
"rural area":	"ሃገረሰብ"			,
"rush":	"ቀልጠፈ"			,
"rush":	"ተሃወኸ"			,
"rusty":	"መራት",
 "sack":	"ሳንጣ"			,
"sacrament":	"ቁርባን"			,
"sacrifice":	"መስዋእቲ"			,
"sacrifice":	"ተሰወአ"			,
"sad":	"ጉሁይ"			,
"sadness":	"ጓሂ"			,
"safe":	"ድሕንነት"			,
"sailing ship":	"ጋንጽላ መንርከብ"			,
"sailor":	"ባሕረኛ"			,
"saint":	"ጻድቕ"			,
"salad":	"ሳላጣ"			,
"salary":	"መሃያ"			,
"saliva":	"ጥፍጣፍ"			,
"salt":	"ጨዉ"			,
"sample":	"መርኣያ"			,
"sand":	"ሑጻ"			,
"satisfy":	"ኣዐገበ"			,
"Saturday":	"ቀዳም"			,
"save":	"ኣድሓነ"			,
"save up":	"ቆጠበ"			,
"saving":	"ውህላለ ገንዘብ"			,
"saviour":	"መድሓኒ"			,
"saw off":	"ሓርሓረ"			,
"say":	"በለ"			,
"say again":	"ደገመ"			,
"scarf":	"ሻርባ"			,
"scent":	"ጨና"			,
"schedule":	"ዓውደ ኣዋርሕ"			,
"school":	"ቤተ ትምህርቲ"			,
"school teacher":	"መም ህር"			,
"schoolboy":	"ተማሃራይ"			,
"schoolgirl":	"ተማሃሪት"			,
"science":	"ሳየንስ"			,
"science":	"ኣስተዋጽኦ ፍልጠት"			,
"scissors":	"መቐስ"			,
"score":	"ነጥቢ"			,
"scrape":	"ሓኸኸ"			,
"scratch":	"ሓንፈጠ"			,
"screen":	"ዓለባ ምርኢት"			,
"screwdriver":	"ዘዋር መስኒ"			,
"script":	"ጽሕፈት"			,
"sculpture":	"ቅርጺ"			,
"sea":	"ባሕሪ"			,
"seal":	"ማሕተም"			,
"seam":	"ስፍየት ክዳን"			,
"search":	"ምድላይ"			,
"search":	"ደለየ"			,
"season":	"ክፍለ ዓመት"			,
"seat":	"ኮፍ መበሊ"			,
"seat":	"ኣንበረ"			,
"second grade":	"ካልኣይ ክፍሊ"			,
"secondary":	"ካልኣዊ"			,
"secondary school":	"ካልኣይ ደረጃ"			,
"secret":	"ምስጢር"			,
"secretary":	"ጸሐፊ"			,
"secretary":	["ጸሓፋይ"	,"ጸሓፊት"]		,
"section":	"ክፍሊ"			,
"security":	"ውሕስነት"			,
"see":	"ረኣየ"			,
"seed":	"ፍረ"			,
"seem":	"መሰለ"			,
"select":	"መረጸ"			,
"selection":	"ምርጫ"			,
"self confidence":	"መተኣማመኒ"			,
"self control":	"ርግኣት"			,
"sell":	"ሸየጠ"			,
"seller":	"ሸያጣይ"			,
"seller":	"ሸያጢት"			,
"send":	"ስደደ"			,
"send to sleep":	"ኣደቀሰ"			,
"sender":	"ሰዳዳይ"			,
"senior":	"ሽማግለ"			,
"sensational":	"ኣድናቒ"			,
"sensitive":	"ተነካኢ"			,
"separate":	"ፈለየ"			,
"separation":	"ምፍልላይ"			,
"September":	"መስከረም"			,
"serenity":	"ርግኣት"			,
"sergeant":	"ሰርገንቲ"			,
"seriously":	"ብጥንቃቐ"			,
"servant":	["ኣገልጋሊት"	,"ከዳሚት"]		,
"servant":	"ኣገልጋሊ"			,
"serve":	"ኣገልገለ"			,
"service":	"ጽቡቕ ግብሪ"			,
"set":	"ኣቐመጠ"			,
"set right":	"ኣቕነዐ"			,
"set up":	["ኣትከለ"	,"ሰርዐ"]		,
"set up again":	"ኣቕነዐ"			,
"settle":	"ተቖጻጸረ"			,
"settle down":	"ኣትከለ"			,
"seven":	"ሸውዓተ"			,
"seventeen":	"ዓሰርተ ሸውዓተ"			,
"seventh grade":	"ሻቡዓይ ክፍሊ"			,
"seventy":	"ሰብዓ"			,
"several":	"ሓያሎ"			,
"severity":	"ጽኑዕ ምክትታል"			,
"sew":	"ሰፈየ"			,
"sewing":	"ስፍየት ክዳን"			,
"shade":	"ጽላሎት"			,
"shadow":	"ጽላሎት"			,
"shake":	"ነቕነቐ"			,
"shame":	"ሕፍረት"			,
"shameful":	"ዘሕፍር"			,
"shape":	"ቅርጺ"			,
"share":	"መቐለ"			,
"sharp":	"ቅጢን ድምጺ"			,
"sharpen":	"ከምከመ"			,
"shatter":	"ሰበረ"			,
"shave":	"ላጸየ"			,
"she":	"ንሳ"			,
"sheep":	"በጊዕ"			,
"sheep pen":	"እንዳ ኣባጊዕ"			,
"sheet":	"ኣንሶላ"			,
"sheet paper":	"ፎልዮ"			,
"shelter":	"ዓቀበ"			,
"shelter":	"ተዓቖበ"			,
"shepherd":	"ጓሳ"			,
"shine":	"ኣንጸባረቐ"			,
"shining bright":	"ኣንጸባረቒ"			,
"ship":	"መርከብ"			,
"shipper":	"ሰዳዳይ"			,
"shirt":	"ካሚሻ"			,
"shiver":	"ምንቅጥቃጥ"			,
"shiver":	"ኣንቀጥቀጠ"			,
"shoe":	"ሳእኒ"			,
"shoemaker":	"ሰራሕ ሳእኒ"			,
"shoes":	"ሳእኒ ለበሰ"			,
"shoot":	"ተኰሰ"			,
"shore":	"ደንደስ"			,
"short":	"ሓጺር"			,
"short story":	"ወረ"			,
"shortage":	"ጉዳል"			,
"shorten":	"ኣሕጸረ"			,
"shoulder":	"መንኩብ"			,
"shovel":	"ባዶላ"			,
"show":	"ኣርኣየ"			,
"shower":	["ዝናብ"	,"ዝናብ መሕጸቢ"]		,
"shudder":	"ኣንፈጥፈጠ"			,
"shut":	"ዕጽዉ"			,
"shut":	"ዓጸወ"			,
"shutter":	"መጋረጀ"			,
"shy":	"ሓፋር"			,
"sick":	"ሕሙም"			,
"sidewalk":	"መንገዲ ኣጋር"			,
"sigh":	"ኡፍ በለ"			,
"sight":	"ርእየት"			,
"sign":	"ምልክት"			,
"signal":	"ምልክት"			,
"signature":	"ክታም"			,
"silence":	"ጸጥታ"			,
"silent":	"ጸጥተኛ"			,
"silver":	"ብሩር"			,
"silvery":	"ብሩር ዝተቀብአ"			,
"similar":	"ዝመስሰል"			,
"similar":	"ከም"			,
"simple":	"ቀሊል"			,
"simplify":	"ኣቃለለ"			,
"simply":	"ብቐሊል"			,
"sin":	"ሓጥያት"			,
"sincerely":	"ብቕንዕና"			,
"sincerity":	"ቅንዕና"			,
"sing":	"ደረፈ"			,
"singer":	"ደራፊት"			,
"singer":	"ደራፊ"			,
"single":	"ዘይምርዕዉ"			,
"sinister":	"እከይ"			,
"sink":	"ጠሓለ"			,
"sinus":	"ስርኖ"			,
"sister":	"ሓብቲ"			,
"sit":	"ኮፍ"			,
"sit down":	"ኮፍ በለ"			,
"site":	"ቦታ"			,
"situation":	"ኩነታት"			,
"six":	"ሽዱሽተ"			,
"six months":	"መንፈቕ"			,
"sixteen":	"ዓሰርተ ሽዱሽተ"			,
"sixth grade":	"ሻዱሻይ ክፍሊ"			,
"sixty":	"ስሳ"			,
"size":	"ዓቐን"			,
"skate":	"ኣንሻተተ"			,
"skeleton":	"ኣስካሮን"			,
"sketch":	"ንድፊ"			,
"skilful":	"ክኢላ"			,
"skill":	"ክእለት"			,
"skilled worker":	"ሰራሕተኛ"			,
"skin":	"ቆርበት"			,
"skirt":	"ጎና"			,
"skull":	"ሽክና ርእሲ"			,
"slain":	"ሓረደ"			,
"slam":	"ገምታ"			,
"slaughter":	"ሓረደ"			,
"slave":	"ባርያ"			,
"sleep":	"ድቃስ"			,
"sleep":	"ደቀሰ"			,
"slide":	"ኣንሻተተ"			,
"slight":	"ፈኲስ"			,
"slightly":	"ብቐሊሉ"			,
"slip":	"ኣንሻተተ"			,
"slipper":	"ሸበጥ"			,
"slippery":	"ሸትሕትሖ"			,
"slope":	["ቁልቁለት"	,"ዓቐብ"]		,
"slowly":	"ብቐስ"			,
"slowness":	"ዝሕለት"			,
"small":	["ንእሽቶ"	,"ንእሽተይ"]		,
"small finger":	"ሕንጢል"			,
"small intestine":	"ማዓንጣ"			,
"small toe":	"ሕንጢል ሕንጥሊቶ"			,
"smart":	"ጎራሕ"			,
"smell":	"ጨነወ"			,
"smelting":	"ምሕቃቐ"			,
"smile":	"ፍሽኽታ"			,
"smile":	"ፍሽኸታ"			,
"smoke":	"ትኪ"			,
"smoke":	"ኣትከኸ"			,
"smooth":	"ልሙጽ"			,
"snack":	"ጠዓሞት"			,
"snail":	"ኣረነ"			,
"snake":	"ተመን"			,
"so much":	"ብጣዕሚ"			,
"soak":	"ኣጥለለ"			,
"soap":	"ሳሙና"			,
"soccer":	"ኩእሶ እግሪ"			,
"social":	"ማሕበራዊ"			,
"society":	"ሕብረት ሰብ"			,
"sock":	"ካልሲ"			,
"soft":	"ልምሉም"			,
"soil":	"ባይታ"			,
"soldier":	"ወተሃደር"			,
"sole of the foot":	"ከብዲ እግሪ"			,
"solely":	"ጥራይ"			,
"solid":	"ድሩቕ"			,
"solution":	"መፍትሒ"			,
"solve":	"ፈተሐ"			,
"something":	"ገለ ነገር"			,
"sometimes":	"ንሓንሳብ"			,
"son":	"ወዲ"			,
"song":	"ደርፊ"			,
"soon":	"ብቑልጡፍ"			,
"sore":	"ቁስሊ"			,
"sorrow":	"ጸበባ"			,
"sorry":	"ይቕረታ"			,
"sort":	"ዓይነት"			,
"sort":	"መመየ"			,
"soul":	"ነፍሲ"			,
"sound":	"ድምጺ"			,
"soup":	"መረቕ"			,
"south":	"ደቡብ"			,
"southern":	"ደብባዊ"			,
"space":	"ቦታ"			,
"spade":	"ባዶላ"			,
"spare":	"ቆጠበ"			,
"spare time":	"ግዜ ዕረፍቲ"			,
"sparing with be":	"ቆጠበ"			,
"sparkle":	"ኣንጸባረቐ"			,
"speak":	"ተዘረበ"			,
"speaker":	"ተዛራባይ"			,
"special":	"ፍሉይ"			,
"spectator":	"ተዓዛቢ"			,
"speech":	"ዘረባ"			,
"speed":	"ቅልጣፈ"			,
"spell":	"ጸሓፈ"			,
"spend":	"ሓሸሸ"			,
"spice":	"ቀመማት"			,
"spider":	"ሳሬት"			,
"spinach":	["ሓምሊ"	,"ስፐናቺ"]		,
"spine":	"ዓንዲ ሕቔ"			,
"spirit":	"መንፈስ"			,
"spit":	"ጡፍ በለ"			,
"splendid":	"ግሩም"			,
"split up":	"ነቶገ"			,
"spoil":	"ኣባላሸወ"			,
"spoon":	"ማንካ"			,
"sport":	"ስፖርት"			,
"spot":	"ንጣብ ርስሓት"			,
"spot":	"ነጠበ"			,
"spread":	"ነዝሐ"			,
"square":	"ትርብዒት"			,
"squeeze":	"ጸሞቐ"			,
"squirrel":	"ምጹጽላይ"			,
"stable":	"እንዳ ኣፍራስ"			,
"stadium":	"እስታዲዩም"			,
"staff":	"ሰራሕተኛታት"			,
"stage":	"መድረክ"			,
"stain":	"ንጣብ ርስሓት"			,
"staircase":	"መደያይቦ"			,
"stairs":	"መደያይቦ"			,
"stalk":	"ጉንዲ"			,
"stamp":	"ቲምብር"			,
"stand":	"ደው"			,
"stand up again":	"ቀንዐ"			,
"standing":	"ጠጠው"			,
"stapler":	"ስተፕረ"			,
"start":	"መጀመርታ"			,
"start":	"ጀመረ"			,
"state":	"መንግስቲ"			,
"statement":	"ኣዋጅ"			,
"station":	"መዕረፍ ባብር"			,
"statue":	"ሓወልቲ"			,
"stay":	"ጽንሒት"			,
"stay away from":	"ቦኾረ"			,
"steal":	"ሰረቐ"			,
"steam":	"ሃፋ"			,
"step":	"ስጉምቲ"			,
"step back":	"ኣንሰሓበ"			,
"step ladder":	"መሳልል"			,
"stew lentils":	"ትምቲሞ"			,
"stick":	"በትሪ"			,
"stiff":	"ነቓጽ"			,
"still":	["ጌና"	,"እንደገና"]		,
"sting":	"መንከሲ"			,
"sting":	"ነኸሰ"			,
"stir":	"ዞረ"			,
"stitch":	"ሰፈየ"			,
"stock":	"ከዘነ"			,
"Stomach":	"ከብዲ"			,
"stone":	"እምኒ"			,
"stool":	"መሳልል"			,
"stop":	"ደው ኣበለ"			,
"store":	"ድኳን"			,
"storm":	"ማዕበል"			,
"stormy":	"ማዕበላዊ"			,
"story":	"ዛንታ"			,
"stove":	"እቶን"			,
"strange":	"ዘይፍሉጥ"			,
"strap":	"ኣሰረ"			,
"stream":	"ዛራ"			,
"street":	"ጎደና"			,
"stretch":	"መጠጠ"			,
"strict":	"ጽኑዕ"			,
"strictness":	"ጽኑዕ ምክትታል"			,
"strike":	"ወቕዐ"			,
"stroke":	"ጎንጺ"			,
"stroll":	"መዛወሪ"			,
"stroller":	"ተዛዋሪ"			,
"strong":	"ሓያል"			,
"struggle":	"ቃልሲ"			,
"student":	"ተማሃሪት"			,
"student":	"ተማሃራይ"			,
"studio":	"ቤተ ዕዮ"			,
"study":	"መጽናዕቲ"			,
"study":	"ኣጽንዐ"			,
"stupid":	"ደንቆሮ"			,
"stupidity":	"ዕሽነት"			,
"style":	"ኣገባብ"			,
"subject":	"ዛዕባ"			,
"subscriber":	"ምዝጉብ"			,
"subtraction":	"ምጉዳል"			,
"suburbs":	"ጎደቦ"			,
"succeed":	"ተዓወተ"			,
"success":	"ዓወት"			,
"suck":	"መጸየ"			,
"sudden":	"ሃንደበት"			,
"suddenly":	"ብሃንደበት"			,
"suffer":	"ተሳቐየ"			,
"suffering":	"ስቓይ"			,
"sufficient":	"እኹል"			,
"sufficient":	  "ኣኸለ"			,
"sugar":	"ሽኮር"			,
"suggest":	"ሓበረ"			,
"suit":	"ክዳን"			,
"suitcase":	"ባልጃ"			,
"sum":	"ድምር"			,
"summer":	"ሓጋይ"			,
"summon to law":	"ኣጸወዐ"			,
"sun blind":	"ገራድ ብርሃን"			,
"Sunday":	"ሰንበት"			,
"superintendent":	"ሓላው ርሻን"			,
"superior":	"ብሉጽ"			,
"supervise":	"ተዓዘበ"			,
"supplies":	"ነገር ንዋት"			,
"support":	"መደግፊ"			,
"support":	"ደገፈ"			,
"suppose":	"መሰሎ"			,
"suppress":	"ኣጥፈአ"			,
"suppression":	"ምጥፋእ"			,
"supreme":	"ዝለዓለ"			,
"sure":	"ርግጸኛ"			,
"sureness":	"ርግጽነት"			,
"surprise":	"ሃንደበት"			,
"surprising":	"ሃንደበታዊ"			,
"surrender":	"ኡዱ ሃበ"			,
"surroundings":	["ጥቓ"	,"ኣከባቢ"]		,
"survive":	"ደሓነ"			,
"suspect":	"ጠርጠረ"			,
"suspicion":	"ጥርጥር"			,
"swallow":	"ወሓጠ"			,
"swamp":	"ዓዘቕቲ"			,
"swamp":	"ኣጥለቕለቐ"			,
"swan":	"ስዋን"			,
"swarm":	"ዕስለ"			,
"swear":	"መሓለ"			,
"sweat":	["ረሃጽ"	,"ርሀጽ"]		,
"sweat":	"ረሃጸ"			,
"sweet":	"ምቁር"			,
"swim":	"ሓምበሰ"			,
"swimming":	"ምሕምባስ"			,
"swing":	"ሰለል"			,
"switch":	"ለወጠ"			,
"switch on":	"ወለዐ"			,
"symbol":	"ምልክት"			,
"sympathy":	"ድንጋጸ"			,
"system":	"ቀጥዒ"			,
"table":	"ጣውላ"			,
"tablecloth":	"መኽደኒ ጣውላ"			,
"tail":	"ጭራ"			,
"take":	"ወሰደ"			,
"take off one's hat":	"ጉልባብ ቀልዐ"			,
"tale":	"ጽንጽዋይ"			,
"talent":	"ክእለት"			,
"talk":	"ዘረባ"			,
"talk":	"ተዛረበ"			,
"talk to each other":	"ተመያየጠ"			,
"talkative":	"ሃታፍ"			,
"tall":	"ነዊሕ"			,
"tangled":	"ጽዑቕ"			,
"tape":	"መጥመሪ"			,
"tart":	"ዶልሺ ፍረታት"			,
"taste":	"ጠዓመ"			,
"tasteless":	"መቐረት ዘይብሉ"			,
"tax":	"ግብሪ"			,
"taxation":	"ግብሪ"			,
"tea":	"ሻሂ"			,
"teach":	"መሃረ"			,
"teacher":	["መምህር"	,"ፕሮፈሰር"]		,
"team":	"ጋንታ"			,
"tear":	"ንብዓት"			,
"tear up":	"ቀደደ"			,
"tears":	"ንብዓት"			,
"tease":	"ሓጨጨ"			,
"teeth":	"ስኒ"			,
"teff":	"ጣፍ"			,
"telephone":	"ተለፎን"			,
"television":	"ተለቭጅን"			,
"tell":	"ነገረ"			,
"temperature":	"ሙቐት"			,
"temple":	"ቤተ መቕደስ"			,
"temporalis muscle":	"መታልሕ"			,
"temporary":	"ግዚያዊ"			,
"temptation":	"ፈተነ"			,
"ten":	"ዓሰርተ"			,
"tenant":	"ተኻራይ"			,
"tendon":	"ጂማት"			,
"tent":	"ተንዳ"			,
"tenth":	"ዓስራይ"			,
"tenth grade":	"ዓሽራይ ክፍሊ"			,
"terrible":	"ዘሰንብድ"			,
"terrify":	"ኣፍረሐ"			,
"territory":	"ግዝኣት"			,
"test":	"ፈተና"			,
"testify":	"መስከረ"			,
"testimony":	"ምስክርነት"			,
"thank":	"ኣመስገነ"			,
"thank you":	"የቐንየለይ"			,
"thankless":	"ዘየመስግን"			,
"that":	["እቲ"	,"እቲኣቶም"]		,
"thatched cottage":	"ኣጉዶ"			,
"thaw":	"ምሕቃቐ"			,
"theatre":	"ቲያትር"			,
"theft":	"ስርቂ"			,
"theirs":	"ናተን"			,
"theirs":	"ናቶም"			,
"then":	"ቀጺሉ"			,
"theory":	"ክልስ ሓሳብ"			,
"there":	"ኣብቲ"			,
"thermometer":	"ተርሞመተር"			,
"they":	"ንሳተን"			,
"they":	"ንሳቶም"			,
"thick":	"ድልዱል"			,
"thieving":	"ሰራቒ"			,
"thigh":	"ሰለፍ"			,
"thin":	["ረቂቕ"	,"ቀጢን"]		,
"thing":	"ኣቕሓ"			,
"think":	"ሓሰበ"			,
"think up":	"ገመተ"			,
"third":	"ሳልሳይ"			,
"third":	"ሲሶ"			,
"third grade":	"ሳልሳይ ክፍሊ"			,
"thirst":	"ጽምኢ"			,
"thirsty":	"ጽሙእ"			,
"thirteen":	"ዓሰርተ ሰለስተ"			,
"thirty":	"ሰላሳ"			,
"thorn":	"እሾኽ"			,
"thorny":	"ኣሻኹ"			,
"thought":	"ሓሳብ"			,
"thousand":	"ሽሕ"			,
"thread":	"ፈትሊ"			,
"threaten":	"ኣፈራርሀ"			,
"three":	"ሰለስተ"			,
"thrilled":	"ኣንቀጥቀጠ"			,
"throat":	"ጎሮሮ"			,
"throw":	"ሰንደወ"			,
"throw back":	"ነጸገ"			,
"thunder":	"ነጎዳ"			,
"thunder":	"ነጎደ"			,
"Thursday":	"ሓሙስ"			,
"ticket":	"ቲከት"			,
"tidiness":	"ጽሬት"			,
"tie":	"ጥማር"			,
"tie":	"ኣሰረ"			,
"tiger":	"ነብሪ"			,
"tight":	"ጽቢብ"			,
"tighten":	"ጸቐጠ"			,
"tile":	"መኽደኒ ናሕሲ"			,
"timber":	"ኦም"			,
"time":	["ግዜ"	,"ሰዓት"]		,
"time allowed":	"ድንጓየ"			,
"tiny":	["ንእሽቶ"	,"ንእሽተይ"]		,
"tip":	"ጫፍ"			,
"tire":	"ጎማ"			,
"tire":	"ኣድከመ"			,
"tiredness":	"ድኹም"			,
"tiredness":	"ድኻም"			,
"title":	"ኣርእስቲ"			,
"to try hard":	"ጸዓረ"			,
"tobacco":	"ትንባኾ"			,
"today":	"ሎሚ"			,
"toe":	"ኣጻዕቲ እግሪ"			,
"toe nail":	"ጽፍሪ እግሪ"			,
"toes":	"አጻብዕቲ እግሪ"			,
"toilet":	"መሕጸቢ ቤት"			,
"tolerance":	"ጽሮት"			,
"tomato":	"ኮሚደረ"			,
"tomb":	"መቓብር"			,
"tomorrow":	"ጽባሕ"			,
"ton":	"ቶን"			,
"tone":	"ኣገባብ ኣዘራርባ"			,
"tongue":	"መልሓስ"			,
"tonsil":	"ዓንቐር"			,
"too":	"ከምኡውን"			,
"too many":	"ብዘይመጠን"			,
"too much":	"ብዘይመጠን"			,
"tool":	"መተዓየዩ"			,
"tooth paste":	"መሕጸብ ስኒ"			,
"top":	"ጫፍ"			,
"topic":	"ኣርእስቲ"			,
"torment oneself":	"ተጨነቐ"			,
"tortoise":	"ጎብየ"			,
"total":	"ጠቕላላ"			,
"touch":	"ትንካፈ"			,
"touch":	"ተንከፈ"			,
"touched":	"ደንገጸ"			,
"towel":	"ሽጎማኖ"			,
"town":	"ከተማ"			,
"town hall":	"መዘጋጃ ቤተ"			,
"toy":	"መጻወቲ"			,
"trace":	"ኣሰር"			,
"tractor":	"ሓራሲት መኪና"			,
"trade":	"ንግዲ"			,
"trader":	"ነጋዳይ"			,
"tradition":	"ልምዲ"			,
"traditional":	"ልምዳዊ"			,
"train":	"ባቡር"			,
"train":	"ተዓለመ"			,
"transcript":	"ቅዳሕ"			,
"transfer":	"ቦታ ቀየረ"			,
"transform":	"ቀየረ"			,
"transformation":	"ምልዋጥ"			,
"translate":	"ተርጎመ"			,
"translation":	"ትርጉም"			,
"transmit":	"ኣመሓላለፈ"			,
"trap":	"መጻወድያ"			,
"travel":	"ገሸ"			,
"traveller":	"ገያሻይ"			,
"tray":	"ጓንተራ"			,
"treasurer":	"ተሓዝ ገንዘብ"			,
"treat":	"ኣኣንገደ"			,
"treatment":	"ሕክምና"			,
"treaty":	"ውዕል"			,
"tree":	"ገረብ"			,
"tremble":	"ኣንቀጥቀጠ"			,
"tremendous":	"ተኣምራታዊ"			,
"trench":	"ጉድጓድ"			,
"triangle":	"ስሉስ ኩርናዕ"			,
"trip":	"ጉዕዞ"			,
"tripe":	"ጨጎራ"			,
"triple":	"ሰለስተ ዕጽፊ"			,
"troop":	"ዓሳክር"			,
"trouble":	"ሽግር"			,
"trousers":	"ስረ"			,
"truck":	"መኪና ጽዕነት"			,
"true":	"ሓቂ"			,
"trumpet":	"ጥሩምባ"			,
"trunk":	"ሳንዱቕ"			,
"trust":	"እምነት"			,
"trust":	"ኣመነ"			,
"truth":	"ሓቂ"			,
"try":	"ፈተነ"			,
"Tuesday":	"ሰሉስ"			,
"tuna":	"ቶኖ ዓሳ"			,
"tune":	"ቃነየ"			,
"tunnel":	"ገለርያ"			,
"turkey":	"ታኪን"			,
"turn":	"ተመልሰ"			,
"turning":	"ኣንጎሎ"			,
"turtle":	"ጎብየ"			,
"twelfth grade":	"ዓሰርተ ክልተ ክፍሊ"			,
"twelve":	"ዓሰርተ ክልተ"			,
"twenty":	"ዕስራ"			,
"twilight":	"ጽልግልግ"			,
"two":	"ክልተ"			,
"ugly":	"ግናይ"			,
"umbrella":	"ጽላል"			,
"umpire":	"መንጎኛ"			,
"uncle":	"ሓወቦ"			,
"uncle ":	"ኣኮ"			,
"uncommon":	"ፍሉይ"			,
"underneath":	"ኣብ ትሕቲ"			,
"underpants":	"ሙታንታ"			,
"understand":	"ተረድአ"			,
"understood":	"ፍሉጥ"			,
"undiluted":	"ጽሩይ"			,
"undo":	"ፈተሐ"			,
"uneven":	"ጎባጥ"			,
"unexpected":	"ዘይተጸበኻዮ"			,
"unfit":	"ዘይብቑዕ"			,
"unfortunate":	"ቅርሱስ"			,
"ungrateful":	"ዘየመስግን"			,
"unhappy":	"ዘይሕጉስ"			,
"union":	"ሕብረት"			,
"unite":	"ኣከበ"			,
"united":	"ሕቡራት"			,
"unity":	"ሓድነት"			,
"university":	["ዩኒቨርስቲ"	,"ላዕላይ ደረጃ"]		,
"unknown":	"ዘይፍሉጥ"			,
"unload":	"ኣራገፈ"			,
"unlucky":	"ቅርሱስ"			,
"unmarried":	"ዘይምርዕዉ"			,
"unpleasant":	"ዘየሐጉስ"			,
"unroll":	"ዘርገሐ"			,
"unstick":	"ነቐለ"			,
"untie":	"ፈተሐ"			,
"until":	"ክሳብ"			,
"unwind":	"ዘርገሐ"			,
"unworthy":	"ዘይብቑዕ"			,
"up to":	"ክሳብ"			,
"up":	"ተንሰአ"			,
"up":	"ብፍቓዱ ገደፈ"			,
"uphold":	"ዓቀበ"			,
"upper arms muscles":	"ቅልጽም"			,
"upset":	"ተጨነቐ"			,
"urban":	"ከተማዊ"			,
"urgent":	"ህጹጽ"			,
"urine":	["ሽንቲ"	,"ችንቲ"]		,
"use":	"ተጠቐመ"			,
"useful":	"ጠቓሚ"			,
"uterus":	"ማሕጸን"			,
"vaccine":	"ክታቤት"			,
"value":	"ዋጋ"			,
"vanish":	"ጠፍአ"			,
"varnish":	"ቀብአ"			,
"vegetable":	"ኣትክልታዊ"			,
"vegetable stew":	["ኣልጫ"	,"ዝግኒ"]		,
"vein":	"ሰራዉር"			,
"verdict":	"ፍርዲ"			,
"verify":	"ኣጸረየ"			,
"very much":	"ብጣዕሚ"			,
"veteran":	"ተጋዳላይ"			,
"victim":	"ግዳይ"			,
"victor":	"ዕዉት"			,
"victory":	"ዓወት"			,
"view":	"ርእየት"			,
"village":	"ሃገረሰብ"			,
"vinegar":	"ኣቸቶ"			,
"violet":	"ሊላ"			,
"virgin":	"ድንግል"			,
"Virgin Mary":	"ድንግል ማርያም"			,
"visible":	"ዝረአ"			,
"visit":	"ምብጻቕ"			,
"visit":	"በጽሐ"			,
"visitor":	"በጻሒ"			,
"voice":	"ድምጺ"			,
"vote":	"ኣድመጸ"			,
"vow":	"መሓለ"			,
"vulture":	"ኣሞራ"			,
"wage":	"መሃያ"			,
"wagon":	"ባጎኒ"			,
"wait":	"ተጸበየ"			,
"waiter":	"ኣሰላፊ"			,
"waiting room":	"ክፍሊ መጸበዩ"			,
"waitress":	"ኣሰላፊት"			,
"wake up":	"ተበራበረ"			,
"walk":	"ዙረት"			,
"walk":	"ተዛወረ"			,
"walker":	"ተዛዋሪ"			,
"wall":	"መንደቕ"			,
"wanderer":	"ኮብላሊ"			,
"wandering":	"ኩብለላ"			,
"want":	"ደለየ"			,
"war":	"ውግእ"			,
"warm":	"ውዕውዕ"			,
"warm":	"ኣውዓየ"			,
"warmth":	"ዋዒ"			,
"warn":	"ኣጠንቀቐ"			,
"warning":	"መጠንቀቕታ"			,
"was aware of":	"ፍሉጥ"			,
"wash oneself":	"ተሓጸበ"			,
"wasp":	"ዕኮት"			,
"waste":	"ኣጥፈአ"			,
"wastebasket":	"ዘንቢል"			,
"watch":	"ሰዓት ኢድ"			,
"watch":	"ጠመተ"			,
"water":	"ማይ"			,
"water melon":	"ብርጭቕ"			,
"water spray":	"ንጽጎ ማይ"			,
"water well":	"ዒላ"			,
"wave":	"ማዕበል"			,
"wax":	"ወልወለ"			,
"way down":	"ቁልቁለት"			,
"we":	"ንሕና"			,
"weak":	"ድኹም"			,
"weaken":	"ኣድከመ"			,
"weakness":	"ድኻም"			,
"wealth":	"ሃብቲ"			,
"wealthy":	"ሃብታም"			,
"wear":	"ለበሰ"			,
"weather":	"ንፋስ"			,
"weave":	"ኣለመ"			,
"wedding":	"መርዓ"			,
"wedding ring":	"ካቲም"			,
"Wednesday":	"ሮቡዕ"			,
"weed":	"ሳዕሪ"			,
"week":	"ሰሙን"			,
"weekly":	"ሰሙናዊ"			,
"weight":	"ሚዛን"			,
"welcome":	"ደሓን መጸ"			,
"welcome":	"ደሓን ምጽ"			,
"west":	"ምዕራብ"			,
"western":	"ምዕራባዊ"			,
"wet":	"ኣጥለለ"			,
"whale":	"ዓሳ ኣንበሪ"			,
"what":	"እንታይ"			,
"wheat":	"ስርናይ"			,
"wheel":	"መንኮርኮር"			,
"when":	"መኣስ"			,
"whip":	"ኩርማጅጅ"			,
"whisper":	"ሕሹኽሹኽ"			,
"whisper":	"ሕሹኽሹኽ በለ"			,
"whistle":	"ፊጽፊጽ"			,
"whistle":	"ፋጸየ"			,
"white":	"ጻዕዳ"			,
"why":	"ስለምንታይ"			,
"wicked":	"ሕሱም"			,
"wide":	"ገፊሕ"			,
"widely":	"ብብዚሒ"			,
"widen":	"ኣግፈሐ"			,
"widow":	["ሰብኣያ ዝሞታ"	,"ሰበይቱ ዝመተቶ"]		,
"widowed":	["ሰበይቱ ዝመተቶ"	,"ሰብኣያ ዝሞታ"]		,
"widower":	["ሰበይቱ ዝመተቶ"	,"ሰብኣያ ዝሞታ"]		,
"width":	"ስፍሓት"			,
"wife":	"ሰበይቲ"			,
"wild beasts":	"ኣራዊት"			,
"wild boar":	"መፍለስ"			,
"will":	"ድሌት"			,
"win":	"ዓወት"			,
"win":	"ተዓወተ"			,
"wind":	"ንፋስ"			,
"window":	"መስኮት"			,
"wine":	"ነቢት"			,
"wine harvest":	"እርያ ወይኒ"			,
"wing":	"መንፈርፈር"			,
"winner":	"ዕዉት"			,
"winter":	"ክረምቲ"			,
"wintery":	"ናይ ክረምቲ"			,
"wisdom":	"ልቦና"			,
"wise":	"ለባም"			,
"wish":	"ትምኒት"			,
"wish for":	"ተተምነየ"			,
"withdraw":	"ኣንሰሓበ"			,
"witness":	"ምስክር"			,
"wolf":	"ተኹላ"			,
"woman":	"ሰበይቲ"			,
"wonder":	"ተደነቐ"			,
"wonderful":	"ዘደንቕ"			,
"wood":	"ዕንጸይቲ"			,
"woodcutter":	"ቆራጽ ዕንጸይቲ"			,
"wool":	"ጡጥ"			,
"word":	"ቃል"			,
"work":	"ዕዮ"			,
"workable":	"ስራሕ"			,
"worker":	"ሸቃላይ"			,
"workshop":	"ክፍሊ ስራሕ"			,
"worm":	"ሓሰኻ"			,
"worn":	"ልባስ"			,
"worn out":	"ብላይ"			,
"worried":	"ዝተሻቐለ"			,
"worry":	"ሸቐልቀል"			,
"worry":	"ተጨነቐ"			,
"worse":	"ዝኸፍአ"			,
"worship":	"እምነት"			,
"worth":	"ዋጋ"			,
"worth":	"ክብሪ ዘለዎ"			,
"wound":	["ቁስሊ"	,"መቑሰልቲ"]		,
"wound":	["ኣቑሰለ"	,"ጎድአ"]		,
"wreck":	"ኣዕነወ"			,
"wrinkle":	"ዕጣሮ"			,
"wrinkled":	"ዕጣር"			,
"write":	"ጸሓፈ"			,
"writer":	"ደራሲ"			,
"writing":	"ጽሕፈት"			,
"yard":	"ቀጽሪ"			,
"yarn":	"ፈትሊ"			,
"year":	"ዓመት"			,
"yearly":	"ዓመታዊ"			,
"yellow":	"ቢጫ"			,
"yes":	"እወ"			,
"yesterday":	"ትማሊ"			,
"yet":	"ጌና"			,
"yogurt":	"ሩግኦ"			,
"young":	"መንእሰይ"			,
"youth":	"ንእስነት"			,
"zeal":	"ተመስጦ",
"gide":"wedisegid"
		
}



